### ISSUE TITLE
Failed to update branch

### ISSUE THREAD

**Issue by Timer** [chdsbd/kodiak#100]
https://github.com/zeit/next.js/pull/8020/checks?check_run_id=177364070

There's no reason this branch should've failed to been updated AFAIK.

**Comment by chdsbd** [comment]
These are the logs I have for it. Not sure why Github is saying that.

```
Jul 25 12:24:09 d.848cca00-415f-4d92-b718-b93e1bde6eaa app/web.1:  2019-07-25 16:24.09 could not update branch        repo=zeit/next.js#8020 res=<Response [404]> res_json={'message': 'Base does not exist', 'documentation_url': 'https://developer.github.com/v3/repos/merging/#perform-a-merge'} 
Jul 25 12:24:12 d.848cca00-415f-4d92-b718-b93e1bde6eaa app/web.1:  2019-07-25 16:24.12 could not update branch        repo=zeit/next.js#8020 res=<Response [404]> res_json={'message': 'Base does not exist', 'documentation_url': 'https://developer.github.com/v3/repos/merging/#perform-a-merge'} 
Jul 25 12:24:15 d.848cca00-415f-4d92-b718-b93e1bde6eaa app/web.1:  2019-07-25 16:24.15 could not update branch        repo=zeit/next.js#8020 res=<Response [404]> res_json={'message': 'Base does not exist', 'documentation_url': 'https://developer.github.com/v3/repos/merging/#perform-a-merge'} 
Jul 25 12:24:18 d.848cca00-415f-4d92-b718-b93e1bde6eaa app/web.1:  2019-07-25 16:24.18 could not update branch        repo=zeit/next.js#8020 res=<Response [404]> res_json={'message': 'Base does not exist', 'documentation_url': 'https://developer.github.com/v3/repos/merging/#perform-a-merge'} 
Jul 25 12:24:21 d.848cca00-415f-4d92-b718-b93e1bde6eaa app/web.1:  2019-07-25 16:24.21 could not update branch        repo=zeit/next.js#8020 res=<Response [404]> res_json={'message': 'Base does not exist', 'documentation_url': 'https://developer.github.com/v3/repos/merging/#perform-a-merge'} 
```

**Comment by chdsbd** [comment]
It could be something to do with forks. I haven't played around with those before.

**Comment by Timer** [comment]
Yup, just so you know these PRs have the "allow edits from maintainers" toggle enabled.

**Comment by chdsbd** [comment]
Good to know. I'm going to close this in favor of #104. Has kodiak updated forks in the past for you?

**Comment by Timer** [comment]
I don't believe so -- just trying to use Kodiak on an open source project instead of our internal apps.

**Comment by chdsbd** [comment]
Thanks. That's useful information. I've documented this problem in the [README#known-issues](https://github.com/chdsbd/kodiak#known-issues) until #104 is addressed.

**Comment by chdsbd** [comment]
@Timer It appears that it is only possible to update branches within the same repo through the Github API, so I think the best we can do for this issue is to display a warning to users for affected PRs (PRs from forked repos). 

https://developer.github.com/v3/repos/merging/

**Comment by Timer** [comment]
Thanks for the update @chdsbd! Hopefully GitHub can fix this soon.
