### ISSUE TITLE
support updating pull requests made from forks

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#104]
Github's API doesn't support updating forks: https://developer.github.com/v3/repos/merging/#perform-a-merge

For reference, if it did, we would need to update this code to use the head/repo information of the fork:
https://github.com/chdsbd/kodiak/blob/7375b45e9d095d7532c9401792a15427ab428993/kodiak/pull_request.py#L296-L299

To work around this API limitation I thought we might be able to [clone the fork](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation) and do the update ourselves, but github app permissions are such that even if a PR is marked "Allow edits from maintainers.", our github app installation doesn't have permission to download that fork.

I believe we cannot do anything to implement this feature until github changes their API.

Related #100

**Comment by KaiSzuttor** [comment]
why don't you merge the master and the pull request and push it to a staging branch in the main repo. There is no need do change the fork.

**Comment by chdsbd** [comment]
@KaiSzuttor I think that solution would definitely work, but I don't believe that it would be an appropriate solution for Kodiak. For me Kodiak was built around a GitHub PR centered flow where Kodiak mainly automates the update and merging of PRs. I think having Kodiak create new branches for PRs from forks would not fit with this.

**Comment by KaiSzuttor** [comment]
thanks @chdsbd for the response. That's a pity to hear since that makes your tool useless to pretty much every project on github where almost all PRs come from forks. And that is probably the majority.

How do you use your tool for PRs on the project itself?

**Comment by chdsbd** [comment]
Kodiak can still merge PRs for forks, it just cannot update the branches. I mainly use Kodiak for work, so this limitation doesn’t affect me for the most part. For Kodiak itself most of the PRs are by collaborators on the repo, so we don’t hit this issue.

This limitation is definitely a blocker for using Kodiak on open source repositories, but if we want to be able to use GitHub PR features, I think creating new branches with the changes of a fork would break the regular GitHub PR flow.

I think the simplest solution is for GitHub to allow bots to update branches like regular GitHub users can.

**Comment by KaiSzuttor** [comment]
I just realized that there is the possibility to do exactly what we need via the v3 API (https://developer.github.com/v3/pulls/#update-a-pull-request-branch) but probably it's not allowed in github apps because of the preview state.

**Comment by chdsbd** [comment]
@KaiSzuttor Thanks, that endpoint looks promising. I'll test it out as a replacement for this endpoint that we use now: https://developer.github.com/v3/repos/merging/#perform-a-merge

**Comment by chdsbd** [comment]
I've tested with a GitHub app and https://developer.github.com/v3/pulls/#update-a-pull-request-branch works for updating PRs made from forks! It looks like it may be possible to implement this feature now.

I think the only changes that need to be made are removing this check against forks and refactoring the PR update logic to use the new API call.
https://github.com/chdsbd/kodiak/blob/2f7c26db758f8071e7a8e3154e81f2011d380fa8/kodiak/pull_request.py#L227-L231

https://github.com/chdsbd/kodiak/blob/2f7c26db758f8071e7a8e3154e81f2011d380fa8/kodiak/pull_request.py#L313-L325

Thanks for bringing this API to my attention!

**Comment by KaiSzuttor** [comment]
do you plan to implement the update? we would really be interested in that feature and be willing to support the implementation if needed.

**Comment by chdsbd** [comment]
I plan to implement this and I'm hopeful I can do this in the next week or so.

**Comment by chdsbd** [comment]
#202 has been deployed

**Comment by chdsbd** [comment]
I'm very upset with GitHub at the moment.

It appears that GitHub has changed the [`/update-branch`](https://developer.github.com/v3/pulls/#update-a-pull-request-branch) API to no longer work with forks.

When Kodiak (or any GitHub app) attempts to call `/update-branch` on a PR created from a fork, the GitHub API returns a `422` status code with the body, `{"message":"user doesn't have permission to update head repository","documentation_url":"https://developer.github.com/v3"}`.

Previously, as of #202's release, Kodiak was able to use this API successfully to update PRs made form forks, so it seems like a recent change to the GitHub API has impacted this update branch feature.

I'm not sure what any GitHub app can do to get around this.

I've opened a support request, so hopefully that will go somewhere.

I think in the meantime I'll probably make a change to Kodiak to provide some warning about not being able to update branches from forks.

**Comment by KaiSzuttor** [comment]
> It appears that GitHub has changed the /update-branch API to no longer work with forks.

i just tried locally with ```curl``` and it seemed to work. Are you sure that is was not only temporary?

**Comment by chdsbd** [comment]
@KaiSzuttor Sorry, I should have specified that this change only affects GitHub Apps.

Here’s a repo where I reproduced the error: https://github.com/chdsbd/test_github/pull/1

**Comment by KaiSzuttor** [comment]
That's really annoying. I contacted the github support and asked exactly about whether the beta api is enabled for github apps. The answer has been 'yes' 4 weeks ago :angry:

**Comment by chdsbd** [comment]
GitHub Apps can still use the API update normal PRs, but updating PRs that depend on a fork's branch now returns an error.

As of #202's release, GitHub Apps were able to update all PRs, including ones dependent on forks. So GitHub must have change the API recently to prevent this. ☹️

**Comment by KaiSzuttor** [comment]
https://github.com/espressomd/espresso/pull/3419 it still seems to work on our repository

**Comment by chdsbd** [comment]
@KaiSzuttor thanks for the link.

It appears that `/update-branch` does not work on a pull request from a fork if ["allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) is unchecked, which isn't surprising.

My problem was that I created a fork of a repository I owned to another organization I had permissions for, so when I opened the PR, I didn't have the option for "Allow edits from maintainers".

I'm going to open a new issue to track this.

**Comment by jberryman** [comment]
@chdsbd I'm glad to hear updating forks works for the common case. This is a good differentiator to include in https://kodiakhq.com/docs/prior-art-and-alternatives in my opinion (it's why (I learned after setting it up) bulldozer doesn't work for us)

**Comment by chdsbd** [comment]
@jberryman Thanks for the feedback. That table has definitely been neglected. I'll take a look at adding some more differentiators.

I've created a ticket to track this https://github.com/chdsbd/kodiak/issues/487.
