### ISSUE TITLE
Kodiak avatar too prominent

### ISSUE THREAD

**Issue by staabm** [chdsbd/kodiak#164]
the kodiak avatar image feels a bit to prominent in the commit stream pages.
would be great if the people working on the real stuff would be in the foreground, instead of the bot :-)

https://github.com/redaxo/redaxo/commits/master

![grafik](https://user-images.githubusercontent.com/120441/63416796-65e41000-c400-11e9-897c-c73a02898f15.png)

**Comment by chdsbd** [comment]
To me it looks like the author is in the foreground while kodiak, the committer, is in the background.

I'm not sure we can do anything to change this on our end. It seems like this is just how Github decides to place avatars for authors vs. committers.

**Comment by staabm** [comment]
> I'm not sure we can do anything to change this on our end. It seems like this is just how Github decides to place avatars for authors vs. committers.

thats right. In case the avatar image would be less colorful or something it would stick less into the foreground

**Comment by chdsbd** [comment]
This only applies to the "squash" merge method, but when Kodiak merges a PR, Kodiak is not set as the author or committer, so it should no longer appear in the UI. https://github.com/chdsbd/kodiak/issues/228

**Comment by staabm** [comment]
Right. The issue is resolved. Thx
