### ISSUE TITLE
use kodiak to keep a pull request up 2 date, but dont merge

### ISSUE THREAD

**Issue by staabm** [chdsbd/kodiak#165]
would it be possible to use kodiak in a way that it automatically keeps Pull Requests up 2 date with e.g. the `master` branch but dont merge the results yet?

**Comment by chdsbd** [comment]
This is possible with the `merge.update_branch_immediately` configuration option. See the readme for more details: https://github.com/chdsbd/kodiak#config-with-comments-and-all-options-set

Related: https://github.com/chdsbd/kodiak/issues/120

**Comment by chdsbd** [comment]
Actually, I’m not sure that does what you need. Kodiak would still merge the PR.

**Comment by staabm** [comment]
when using this option, would kodiak keep the branch up2date but dont merge it when e.g. it still requires a "accepted" review from a reviewer?

**Comment by chdsbd** [comment]
correct

**Comment by staabm** [comment]
ok, I think this might work for us. thx for the infos.
