### ISSUE TITLE
Automerge dependabot PRs

### ISSUE THREAD

**Issue by rgreinho** [chdsbd/kodiak#208]
Is it possible to automatically merge PRs coming from dependabot? 

Ideally I would like to use something like what mergify does: <https://doc.mergify.io/examples.html#dependabot>.

**Comment by chdsbd** [comment]
I've seen Kodiak automatically merge PRs opened by dependabot on other projects, but I haven't used dependabot myself.

You may need to configure dependabot based on your Kodiak config.

If you're using Kodiak without requiring an automerge label (`merge.require_automerge_label = false`) then Kodiak should automatically merge dependabot PRs, assuming they pass your GitHub branch protection settings.

If you're using Kodiak with default settings and an automerge label of `"merge it!"`, you can configure this label in the `default_labels` of the [dependabot config](https://dependabot.com/docs/config-file/) so any PR dependabot opens will have the `"merge it!"` label to enable Kodiak.

Hope this helps. Let me know if you have any questions.

**Comment by rgreinho** [comment]
Thanks a lot for the quick answer.

It does help, but the answer does not match our workflow. We use `merge.require_automerge_label = false` but we require at least 1 review approval to merge it. Therefore the dependabot PRs are blocked until a developer approves them manually, which kind of defeats the purpose.

Basically for this use case we want to merge the PR without having to manually approve it:
- if the PR author is `dependabot`
- if all the CI checks passed

Looking at the other issues, it seems that what you mentioned in issue #178 would solve our problem: `merge.username_automerge_whitelist = ['dependabot']` would be used instead of the review approval.

**Comment by chdsbd** [comment]
Looking at #178 a second time I think using a GitHub bot to automatically approve PRs created by certain users would be significantly easier than adding `merge.username_automerge_whitelist` to Kodiak.

The GitHub bot would approve any PR opened by a user (ex: `dependabot`) configured in some whitelist. I think Kodiak could be updated to do this, but it seems like there are already a couple GitHub bots that do this (https://github.com/hmarr/auto-approve-action, https://github.com/dkhmelenko/autoapproval).
The only challenge is that you'd need as many bots as required approving reviews, but I think that should be too hard to do.

To support `merge.username_automerge_whitelist` in Kodiak we'd need to disable the "Require pull request reviews before merging" GitHub branch protection setting (see screenshot below), so we'd need to replicate that functionality in Kodiak. I think replicating "required approving reviews" would be possible, but the other options seem more challenging.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1929960/71563687-c7c51e00-2a61-11ea-91b0-49bdff454beb.png">


Let me know if this helps.

**Comment by rgreinho** [comment]
It does help, thank you very much!

We did not want to explore the route of using extra bots, as we hoped kodiak would be our one size fits all solution for our merging/rebasing/approving problems.

But we are definitely going to investigate using a GitHub Action like the one you recommended (we also found [dependabot-auto-merge-action](https://github.com/ridedott/dependabot-auto-merge-action)) in combination with kodiak.

**Comment by renatoruk** [comment]
Do you maybe have an alternative without actions? How complex would be to implement `merge.username_automerge_whitelist` ?

**Comment by chdsbd** [comment]
I plan to have Kodiak support approving PRs that match a configured whitelist of usernames.

`approve.whitelist = ["dependabot"]`

Is that what you mean by `merge.username_automerge_whitelist`?

**Comment by renatoruk** [comment]
Yep, that's exactly what I meant. Great, looking forward to it!

**Comment by chdsbd** [comment]
This feature has been released as of #268.

An example can be found here: https://kodiakhq.com/docs/recipes#automated-dependency-updates-with-dependabot

> ## Automated dependency updates with Dependabot
> 
> While Dependabot can [automerge dependency updates](https://dependabot.com/docs/config-file/#automerged_updates), this functionality will  not work when "Required approving reviews" is configured via GitHub Branch Protection because the PR needs an approving review.
> 
> Kodiak can help us here by automatically adding an approval to all Dependabot PRs, which will allow Dependabot PRs to be automatically > merged without human intervention.
> 
> ```
> # .kodiak.toml
> version = 1
> 
> [approve]
> auto_approve_usernames = ["dependabot-preview[bot]"]
> ```

The configuration reference can be found here: https://kodiakhq.com/docs/config-reference#approveauto_approve_usernames

**Comment by CaioFML** [comment]
@chdsbd Guys, this doc needs to be fix. The username correct is `dependabot-preview` and not `dependabot-preview[bot]`, because of this I lost all the morning trying to figure out why this new feature isn't working and by intuition I tried to delete `[bot]` and all my PR turns approve! :wink:

**Comment by chdsbd** [comment]
@CaioFML sorry about that. I’ll fix it as soon as possible. Thanks for bringing this to my attention.

**Comment by chdsbd** [comment]
Docs should be fixed as of #288. Thanks again for reporting this issue.
