### ISSUE TITLE
Allow a .kodiak.toml in the .github folder

### ISSUE THREAD

**Issue by rgreinho** [chdsbd/kodiak#223]
Our use case is the following:

A `.github` folder in a repository contains all the GitHub configuration files as well as the settings for some other apps (like the [stale bot](https://github.com/probot/stale) configuration for instance). Our organizations all have a `github.com/<my_organization>/.github` repository which contains the files that each new repository must use. It would be cleaner for us to be able to leave the `.kodiak.toml` file in this directory rather than adding instructions in the README.md saying "*Don't forget to move the `.kodiak.toml` file to the root of the repository*".

**Comment by chdsbd** [comment]
This should be pretty simple to add. I thought Kodiak had support for this but it seems like I never got around to adding it 😄 .

**Comment by rgreinho** [comment]
Thanks! I just gave a shot at a PR (#224).
