### ISSUE TITLE
[Question] Can we configure to remove Kodiak as an author of the commit?

### ISSUE THREAD

**Issue by MaicolBen** [chdsbd/kodiak#228]
Hey! 

Awesome tool! I would love if when the PR is merged, only the original authors remain and kodiak isn't added, I know you can edit authors from the merge through the Github API but I don't know how easy is to remove Kodiak specifically. Another option would be go with #150 solution if it's implemented.

**Comment by chdsbd** [comment]
The GitHub [API for merging a PR](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button) doesn't support specifying authorship, so Kodiak would probably need to clone the repository and do the operations in git before pushing changes.

#150 is similarly complicated to implement because the [GitHub API doesn't support it](https://developer.github.com/v3/pulls/#update-a-pull-request-branch), so Kodiak would also need to clone the repository and use git to do rebase updates.

All in all, this is possible, but not easy.

**Comment by MaicolBen** [comment]
Thanks @chdsbd ! Feel free to close this if it's impossible. I didn't read the codebase to see if it possible, just took the idea from [autosquash](https://github.com/tibdex/autosquash/blob/master/src/autosquash.ts#L306)

**Comment by chdsbd** [comment]
This is feature is doable, so I'm going to leave this issue open.

From the link it seems like autosquash has a different feature where it will extract authors from commit messages associated with a PR and add them as coauthors when merging, which I think is different from what GitHub does. It seems like squashes created by autosquash will have autosquash as an author.

**Comment by MaicolBen** [comment]
> It seems like squashes created by autosquash will have autosquash as an author.

Yeah, you might be right (they state otherwise) but reading the code, they don't get rid of the bot/action author. 

Thank you for considering my request!

**Comment by chdsbd** [comment]
I think this issue may have been solved.

It now seems that for the "squash" merge method, Kodiak is no longer an author or committer. So Kodiak no longer appears in the UI or in the commit log.

I've attached an image and console log to show the change. I think GitHub must have rolled this out in the past few days.


![image](https://user-images.githubusercontent.com/1929960/73507947-87cac100-43a8-11ea-8567-b45bb434a308.png)

```console
$ git log --pretty=fuller
commit 9d98de1d694d21053abd6af81792cc6f04aa622a (HEAD -> master, origin/master, origin/HEAD)
Author:     Steve Dignam <sbdchd@users.noreply.github.com>
AuthorDate: Wed Jan 29 19:12:49 2020 -0500
Commit:     GitHub <noreply@github.com>
CommitDate: Thu Jan 30 00:12:49 2020 +0000

    add(docs): edit url to enable edit button on doc pages (#274)

    With this url, docusaurus adds an Edit button to each doc page.

    rel: https://docusaurus.io/docs/en/site-config.html#editurl-string

commit fa53ae35f7fcdb8e0aa3995bdb37ef469b2a4e30
Author:     Christopher Dignam <chris@dignam.xyz>
AuthorDate: Sun Jan 26 22:03:14 2020 -0500
Commit:     kodiakhq[bot] <49736102+kodiakhq[bot]@users.noreply.github.com>
CommitDate: Mon Jan 27 03:03:14 2020 +0000

    ref: prioritize configuration errors in evaluation (#272)

    Configuration errors should be surfaced before Kodiak acts on a repository.
```

**Comment by MaicolBen** [comment]
Yes! Awesome!!
