### ISSUE TITLE
updates to master don't trigger updates on dependent PRs

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#244]
When new commits are added to the target branch, the open PRs against that branch are not updated, even though `update.always` is configured.
report: https://github.com/chdsbd/kodiak/issues/174#issuecomment-574077658

I tried to reproduce this and I found that when CircleCI is configured, new commits on the target branch trigger a `status` webhook event for that branch, which triggers Kodiak to enqueue events for all the related PRs. I think if CircleCI used the newer GitHub Checks API, this issue would appear.

https://github.com/chdsbd/kodiak/blob/e1f9680f3cd136bd67ffb1a0648c2b756cd98229/kodiak/main.py#L96-L109

I think the fix is to accept a `push` webhook event and use that trigger PR updates.

**Comment by staabm** [comment]
Not sure if related. We dont use CircleCI but GithubActions and TravisCI

**Comment by chdsbd** [comment]
Thanks, that’s helpful. I think those integrations use CheckRuns instead of Statuses, so Kodiak isn’t receiving any status events.

I think accepting push events should fix the issue.
