### ISSUE TITLE
leave a comment when PR contains conflicts

### ISSUE THREAD

**Issue by clxmstaab** [chdsbd/kodiak#276]
we have some long running PRs which kodiak permantly rebases to stay up 2 date with the target branch.

sometimes those PR get stuck because the PR gets into a conflict state.
we dont notice it though that the PR no longer updates because of conflicts.

it would be great if kodiak could leave a comments within the PR so people working on it are aware that the PR cannot be updated automatically anymore because of conflicts

**Comment by chdsbd** [comment]
Do you know if you’re encountering a normal merge conflict or a rebase merge conflict?
There’s [logic to notify about normal conflicts](https://kodiakhq.com/docs/config-reference#mergenotify_on_conflict) but not rebase ones.

Also, when these PRs don’t update is there an error status message from Kodiak?

This may be related: https://github.com/chdsbd/kodiak/issues/222

**Comment by clxmstaab** [comment]
how to differentiate a "merge conflict" from a "rebase merge conflict"?

I guess it might be the "rebase merge conflict" case, because its related to a PR which is blocked by a "WIP:" title

**Comment by chdsbd** [comment]
I think I figured out the issue and this isn't related to rebase conflicts as I first thought.

If you're using `update.always`, you won't get notified about merge conflicts that occur when updating because Kodiak returns before it hits that logic:

https://github.com/chdsbd/kodiak/blob/9d98de1d694d21053abd6af81792cc6f04aa622a/kodiak/evaluation.py#L300-L311

https://github.com/chdsbd/kodiak/blob/9d98de1d694d21053abd6af81792cc6f04aa622a/kodiak/evaluation.py#L373-L388

I think the `notify_on_conflict` config option should be a top level field instead of being nested in the `merge` options because I think a user should always be notified of conflicts.

So we need a new option `notify_on_conflict` that will notify whenever there is a conflict and deprecate `merge.notify_on_conflict`.

I think this new option should resolve your issue.

example:

```toml
# old
[merge]
notify_on_conflict = true

[update]
always = true
```

```toml
# new
notify_on_conflict = true

[update]
always = true
```

**Comment by staabm** [comment]
> I think the notify_on_conflict config option should be a top level field instead of being nested in the merge options because I think a user should always be notified of conflicts.
So we need a new option notify_on_conflict that will notify whenever there is a conflict and deprecate merge.notify_on_conflict.

Sounds reasonable

**Comment by clxmstaab** [comment]
> So we need a new option `notify_on_conflict` that will notify whenever there is a conflict and deprecate `merge.notify_on_conflict`.

will the new option default to "true"? I feel like having this notifactions as an opt-out would be better then to not know them and forget to opt-in?

**Comment by chdsbd** [comment]
I agree that the default should be true. I think to preserve existing behavior, if `merge.notify_on_conflict` is false, `notify_on_conflict` should be disabled unless explicitly enabled.

**Comment by staabm** [comment]
Today we had another case where a PR got stale because of merge conflicts and nobody noticed it

**Comment by chdsbd** [comment]
Okay, I'm going to prioritize adding this feature. It will probably be added by next week.

**Comment by chdsbd** [comment]
Kodiak needs to track if it has already left a comment to prevent it from adding a duplicate.

With `merge.notify_on_conflict`, when Kodiak encounters a conflict it checks that there is an automerge label set, removes it and leaves a comment.

I think a simple solution is to a similar thing here. Kodiak would set some (configurable) label `kodiak:merge-conflict` to mark the PR as in conflict.
On conflict, Kodiak would check that this label is unset, add the label and leave a comment.

Does this solution sound good to you?

**Comment by staabm** [comment]
Sounds good to me

**Comment by chdsbd** [comment]
@staabm Can you clarify what you mean about configuring the automerge label?

Also, I've added a PR to fix this issue in #364.

**Comment by staabm** [comment]
We already have a automerge label configured.

If We configure the same label for the conflict state, would it work that the bot will remove the automerge lAbel, our dev will resolve the conflict and add the automerge-label again (so we dont need 2 separate labels) ?

**Comment by staabm** [comment]
Hmm while reading the newly added PR I got the impression that the alread available `merge.notify_on_conflict` could be what I need.. seems this is also a optin-feature..?

Need to test it..

**Comment by chdsbd** [comment]
@staabm For the PRs that you keep up to date with Kodiak, do you use the automerge label? I was under the impression you didn't want the branch to be merged.

**Comment by staabm** [comment]
We use the automerge label and the WIP PR Title Prefix

**Comment by chdsbd** [comment]
I think a simple solution may be to move this logic up above the `WIP` check.
https://github.com/chdsbd/kodiak/blob/7032785288915dac7c09ce1bed8ab31eee5c7832/bot/kodiak/evaluation.py#L434-L449

I think the benefit of #364 is that it would work for those that don't use automerge labels.

**Comment by chdsbd** [comment]
I'll update this PR when #371 is deployed.

**Comment by chdsbd** [comment]
This change has been deployed.

**Comment by clxmstaab** [comment]
works like a charm, thx!
