### ISSUE TITLE
When using the "squash" merge.method, Kodiak is the only Author of commits

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#300]
![image](https://user-images.githubusercontent.com/1929960/75919895-5e300a00-5e2c-11ea-96dd-e3502d2e4ba5.png)

```
commit 1ef3a1a9c136a4017ab1a3b8c253ee0c07bb481a (HEAD -> master, origin/master, origin/HEAD)
Author: kodiakhq[bot] <49736102+kodiakhq[bot]@users.noreply.github.com>
Date:   Wed Mar 4 19:20:00 2020 +0000
```

Pull requests merged by Kodiak lose their authorship information. I would expect that the author of the PR would be the author of the merged commit.

This issue likely affects rebase and squash merge methods. I think merge commits should be okay.

It seems GitHub has made a change as of four hours ago, because all the commits on my repository have correct authorship. I've opened an issue with GitHub, but they usually take many weeks to respond.

As a fix I think we could add `Co-authored-by` trailers to the merge commit methods to provide some authorship information.

```

Co-authored-by: Christopher Dignam <chdsbd@users.noreply.github.com>
```

EDIT: I've confirmed this does not affect `merge.method = "merge"`, because the merge commit there is correctly authored by Kodiak. This does affect `merge.method = "squash"` and produces a commit like the following.

```
commit b230449aad2db0f0861e90fad1fc3d4e880eb213
tree 7c85b50efe7bc56a760bbaef3e59fc9b1b008400
parent bca45c7579cba5105a68b2097cafe79a91cfd671
author kodiakhq-staging[bot] <50966410+kodiakhq-staging[bot]@users.noreply.github.com> 1583365747 +0000
committer GitHub <noreply@github.com> 1583365747 +0000
```

For `merge.method = "rebase"` it seems that GitHub does the appropriate thing of making the PR author the author of the commit and Kodiak the committer.

```
commit cfe4bff5a2790e1b193f31e22433cf539ff7a33e
tree 330e10789e21a2d5db0f432ded980450c41c7fcf
parent 87e5740931cba0db22cdc7eebd2199823dd6d800
author Christopher Dignam <chris@dignam.xyz> 1583366253 -0500
committer kodiakhq-staging[bot] <50966410+kodiakhq-staging[bot]@users.noreply.github.com> 1583366297 +0000

    5C384535-9DBD-4361-903D-78655ADFC95B
```

**Comment by cristiadu** [comment]
@chdsbd Hey! Sorry to bother you here, but I'm also having this issue on which seems to be a Github change (it affects the whole platform). Can you share the Github issue you created?

**Comment by chdsbd** [comment]
@cristiadu No worries, that's what this issue is for!

Here's a copy of my correspondence with GitHub Support:

> Christopher Dignam
> Mar 4, 8:19 PM UTC
> 
> It seems there has been a regression in commit authorship for GitHub bots as sometime with the past 4 hours.
> 
> Previously if a bot merged a pull request, the commit author would be the user that opened the pull request and the bot would only be the committer. Now the bot is the author.
> 
> This change destroys valuable authorship information and is a negative change from the previous behavior.
    
> <Redacted> (GitHub Developer Support)
> Mar 4, 10:54 PM UTC
> 
> Hi Christopher,
> 
> Thank you for writing in to GitHub Support and I'm sorry you have experienced this problem.
> 
> I've escalated your report to our engineering team for further investigation.
> 
> I can't make any promises around specific changes or updates, but please trust that your report is in good hands.
> 
> If you need anything else, please feel free to reach out again.
> 
> All the best,
> <Redacted>
> GitHub Support

---

I added a [new configuration option](https://kodiakhq.com/docs/config-reference#mergemessageinclude_pull_request_author) this evening to append the GitHub author to pull requests via https://github.com/chdsbd/kodiak/pull/301.

This provides a slight improvement, but we're still left with the GitHub App being the author of the commit.

Example config:

```toml
version = 1

[merge]
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pull_request_author = true
```

**Comment by chdsbd** [comment]
@cristiadu Wow, I didn't realize how huge this issue was. I thought it was just affecting GitHub Apps and the GitHub API but it seems to affect _all_ squash merging 😱 .

**Comment by cristiadu** [comment]
> @cristiadu Wow, I didn't realize how huge this issue was. I thought it was just affecting GitHub Apps and the GitHub API but it seems to affect _all_ squash merging  .

yeah, when using manual triggering of Squash and Merge that is also happening. So even in the UI haha.

Thank you for the report though, I was looking like crazy if someone else saw similar behavior.

**Comment by chdsbd** [comment]
Apparently GitHub is reverting the change, so hopefully the behavior we all love will return soon.

https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/m-p/48960#M10715
