### ISSUE TITLE
Sponsor Logo

### ISSUE THREAD

**Issue by clxmstaab** [chdsbd/kodiak#314]
hey!

would you be open for adding our company logo with a link to the projects readme, since we sponsoring your work on the bot?

**Comment by chdsbd** [comment]
sounds fair

**Comment by staabm** [comment]
I will open a PR

**Comment by clxmstaab** [comment]
I will open a PR

**Comment by clxmstaab** [comment]
just published a blog post mentioning both of you guys and the project

https://www.complex-it.de/complex-unterstuetzt-open-source-maintainer/

Thanks!

**Comment by chdsbd** [comment]
Thank you 😊
