### ISSUE TITLE
Disable Auto Update.

### ISSUE THREAD

**Issue by Negan1911** [chdsbd/kodiak#326]
There's a way to disable auto-update of branch?, since I use Kodiak to auto-merge PR's from dependabot, most of the times everything works well.

But when kodiak updates a Dependabot PR it makes Dependabot not being able to self-update his PR's, or, on cases where the PR is superseeded, not close the updated-pr.

I would love to be able to use Kodiak for auto-merge PR's, but leverage Dependabot for updating his PR's.

Both disabling auto-update or blacklisting/whitelisting auto-update authors would work.
Thanks for your great product!

**Comment by chdsbd** [comment]
Thanks for raising this issue. I think a new config option could be added to make this work.

```toml
update.username_blacklist = ['dependabot-preview']
```

**Comment by Negan1911** [comment]
That would be awesome!

**Comment by Negan1911** [comment]
This has been fixed by #327 .
