### ISSUE TITLE
Does not handle renamed jobs

### ISSUE THREAD

**Issue by sanmai-NL** [chdsbd/kodiak#360]
After renaming a GitHub Actions job, Kodiak waits for a status report of the job with the orginal name and the new name. In the following screenshot, 'build' is the old name and 'qa_controls' the new name.

![image](https://user-images.githubusercontent.com/3374183/81071936-b3000780-8ee5-11ea-9d61-1a2acb384c06.png)

**Comment by chdsbd** [comment]
I think you need to update the GitHub Branch Protection setting to not make `build` required.

You would uncheck the status check called "build" that says `Required` next to it.

<img width="768" alt="Screen Shot 2020-05-05 at 9 48 16 AM" src="https://user-images.githubusercontent.com/1929960/81073473-afed2300-8eb5-11ea-9c57-3ff0971c4134.png">

Here's some relevant docs from GitHub: https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks

Let me know if you have any questions.

**Comment by sanmai-NL** [comment]
Oh, so this is a GitHub issue? Then it's not a bug. It's a bit troublesome though.
