### ISSUE TITLE
Support Draft PRs in addition to PRs with WIP-like titles

### ISSUE THREAD

**Issue by sanmai-NL** [chdsbd/kodiak#362]
[Draft](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request) PRs are a formal way of saying a PR is not ready for merging and/or review. I like that this is a UI feature. For less experienced programmers, crafting a title to match the WIP-regex is harder to learn and remember.

**Comment by chdsbd** [comment]
Kodiak supports draft PRs. If a PR is a draft state Kodiak will not be able to merge it. Here's an example of what it looks like.
<img width="642" alt="Screen Shot 2020-05-05 at 6 42 41 PM" src="https://user-images.githubusercontent.com/1929960/81123070-40505580-8f00-11ea-9907-e4ca018eed71.png">

**Comment by sanmai-NL** [comment]
@chdsbd: that's great. Is this documented though? I only found https://kodiakhq.com/docs/config-reference#mergeblacklist_title_regex.

**Comment by chdsbd** [comment]
Good point, I'll look at better documenting this behavior.
