### ISSUE TITLE
[Self-hosted] Error when pulling docker image

### ISSUE THREAD

**Issue by MaicolBen** [chdsbd/kodiak#376]
When I do `docker pull cdignam/kodiak`

It throws  `Error response from daemon: manifest for cdignam/kodiak:latest not found: manifest unknown: manifest unknown`

**Comment by sbdchd** [comment]
The build process for the docker containers tags them with the Git SHA. It doesn't use the `latest` tag since the deployments work off of discrete versions.

So it should work if you specific the Git SHA of the version you want to run as the tag. 

https://hub.docker.com/r/cdignam/kodiak/tags

**Comment by MaicolBen** [comment]
Yeah, that worked! thank you
