### ISSUE TITLE
Complement automerge label with not_automerge label

### ISSUE THREAD

**Issue by sanmai-NL** [chdsbd/kodiak#384]
**Problem**
Adding labels to each PR is a chore, but on the other hand, setting `merge.require_automerge_label` to `true` gives more control over when Kodiak comes into play. 

**Solution**
In addition to `merge.require_automerge_label`, provide `merge.require_not_automerge_label`. When true, Kodiak doesn't merge a PR when it has the label set in `merge.not_automerge_label`.

**Comment by chdsbd** [comment]
Could you use `merge.require_automerge_label = false` with [`merge.blacklist_labels`](https://kodiakhq.com/docs/config-reference#mergeblacklist_labels)? Also, [`merge.blacklist_title_regex`](https://kodiakhq.com/docs/config-reference#mergeblacklist_title_regex) might be useful too.

**Comment by sanmai-NL** [comment]
Ahh, obviously yes. I've read the config page multiple times but perhaps the 'blacklist' name distracted here.
