### ISSUE TITLE
Use whatever PR merge method is allowed on repo if there's only one

### ISSUE THREAD

**Issue by gnarea** [chdsbd/kodiak#387]
First of all, thanks for building kodiak and making it available!

I configure all my repos to only allow squash merges and I wish I could just use the minimal config file with just `version = 1`, and kodiak detected that it should use squash commits.

However, it currently fails because the merge method is the default.

**Comment by chdsbd** [comment]
Great idea. This should be any easy change.

**Comment by chdsbd** [comment]
I'll update this issue when #464 has been deployed.

**Comment by chdsbd** [comment]
#464 has been deployed to production. If `merge.method` is not configured, Kodiak will use the first valid merge method in the repository based on the list "merge", "squash", "rebase".

**Comment by gnarea** [comment]
Thank you so much!
