### ISSUE TITLE
[Question] is it possible to use kodiak on non-protected branch

### ISSUE THREAD

**Issue by kocoten1992** [chdsbd/kodiak#396]
Hi @chdsbd,

Is it possible to use kodiak on non-protected branch, I couldn't find it on docs, for example, on `.kodiak.yml`

```
...
branch = master
...
```

**Comment by chdsbd** [comment]
It's not super well documented but Kodiak intentionally requires branch protection (https://kodiakhq.com/docs/troubleshooting#branch-protection-requirement).

It would be helpful if you could give an example use case for Kodiak working without branch protection.

**Comment by kocoten1992** [comment]
It's kinda cheap of me, so me and my friends are well known each others, we would never force push `master` branch.

And I though that could have save a few bucks doing that without paying github pro (private repo branch protection required at least github pro).

**Comment by chdsbd** [comment]
Most of Kodiak's behavior is configured using branch protection settings. Without branch protection Kodiak would not update branches or wait for status checks to merge branches. I'm not sure how useful Kodiak would be for you in this setup.

As a workaround to get branch protection, I think if one of you subscribes to GitHub Pro ($4/mo) you could collaborate on that users private repositories, which would have branch protection. This way only one of you needs to subscribe to GitHub.

**Comment by kocoten1992** [comment]
Thank you, I guess that the way to go then :+1:
