### ISSUE TITLE
Support organisation-wide configuration via <org>/.github repositories

### ISSUE THREAD

**Issue by gnarea** [chdsbd/kodiak#403]
I'd love to use Kodiak across all my repos with the same configuration, but it can be very time consuming to port this file across all repos and make sure they don't drift apart.

GitHub already uses `<org>/.github` repos for configuration across all repos, including issue templates, so I think that could be a good place to keep that global config file. [See this example](https://github.com/relaycorp/.github/).

**Comment by chdsbd** [comment]
To support this I think we'd need to update the [event info query](https://github.com/chdsbd/kodiak/blob/ebc30066cfae89e0c545a2a5b1bb16372a9426a4/bot/kodiak/queries.py#L59-L69) to also attempt fetching the configuration from the `.github` repository. We'd also need to update the [default branch lookup](https://github.com/chdsbd/kodiak/blob/ebc30066cfae89e0c545a2a5b1bb16372a9426a4/bot/kodiak/queries.py#L48-L55) to know which branch to look for the .kodiak.toml in the `.github` repository.



For what it's worth, I've found it's rare to change the `.kodiak.toml` once Kodiak is setup.

**Comment by gnarea** [comment]
Hey @chdsbd! Thanks for looking into it.

I installed Kodiak last week and I recall making at least 4 changes to the config file to tweak things as I learn more about how it works and how it interacts with other things I've configured on GitHub (bots, branch protections, etc). It should be stable now, but this meant I've had to port those changes to other repos by hand, which is why some form of global configuration would've come in handy.

Using the `.github` repository is an example. An alternative could be to allow extending an external TOML file from a URL or another repo, although I suspect it might introduce more complexity. It also wouldn't be as nice in my use case because I want all repos to use Kodiak and use the same config.

**Comment by staabm** [comment]
We use a simple github action to sync files between repositores based on golden master files.

Thats pretty easy and also has the benefit that it better works for cases where you don‘t want files from the `.github` repo to work with all of your reposes.
Also it works for any file, not just those supporting the `.github` repo
