### ISSUE TITLE
Don't merge draft PRs

### ISSUE THREAD

**Issue by mohsen1** [chdsbd/kodiak#404]
https://github.com/zeit/next.js/pull/13193

I was surprised to see this PR was merged. Work wasn't completed actually

**Comment by chdsbd** [comment]
It appears [`merge.require_automerge_label`](https://kodiakhq.com/docs/config-reference#mergerequire_automerge_label) is disabled on that repository, so as long as the pull request meets all GitHub Branch Protection requirements it will be merged.

https://github.com/zeit/next.js/blob/canary/.github/.kodiak.toml#L6

**Comment by chdsbd** [comment]
Enabling `merge.require_automerge_label` would make it so Kodiak only merges pull requests with the automerge label, but if this can't be changed, there's a couple workarounds.

One workaround is to move the pull request into a "draft" state. GitHub does not allow draft pull requests to be merged.

Another option is to put "WIP:" in the title, which will prevent Kodiak from merging the pull request based on [`merge.blacklist_title_regex`](https://kodiakhq.com/docs/config-reference#mergeblacklist_title_regex).

**Comment by mohsen1** [comment]
Thank you for the links! I must've clicked "Ready for review" by accident. GitHub is not showing when that happened in timeline so I'm not sure if I did it or someone else. Turns out GitHub doesn't allow merging draft PRs from the UI. if there is a bug in GitHub API that allows to do that then maybe this is an actual issue, otherwise I think this is a false alarm 

Thanks! 💞
