### ISSUE TITLE
Deleting branches that contain a "#" in their name does not work

### ISSUE THREAD

**Issue by SimonTheLeg** [chdsbd/kodiak#407]
Hi all,

we've enabled the `delete_branch_on_merge = true`. This usually works fine, but if the branch contains a "#" character (which coincidentally is the ID our ticketing system uses), then it will fail to delete the branch with the following message.

```
kodiak-578cd6577f-ts4n4 kodiak INFO kodiak.pull_request:pull_request.py:199 event='delete_branch' branch_name='feature/#12345-branch-sanitized' install='8881465' number=32 owner='meshcloud' repo='repo-sanitized'
kodiak-578cd6577f-ts4n4 kodiak INFO kodiak.pull_request:pull_request.py:208 event='branch already deleted, nothing to do' install='8881465' number=32 owner='meshcloud' repo='repo-sanitized' request_body=None request_method='DELETE' request_url='https://api.github.com/repos/meshcloud/repo-sanitized/git/refs/heads/feature/#12345-branch-sanitized' res=<Response [422]> response_content=b'{"message":"Reference does not exist","documentation_url":"https://developer.github.com/v3/git/refs/#delete-a-reference"}' response_status_code=422

```

My guess is since the "#" is part of the URL's path, maybe the GitHub API expects the character to be escaped?

**Comment by chdsbd** [comment]
Yeah, I don’t think branch names get escaped. As a workaround you could enable branch deletion on merge through the GitHub UI.

**Comment by chdsbd** [comment]
A new container should be available in Docker Hub for you to use (`cdignam/kodiak:237065307089cf66836d3fc7f1dca38f2a210c17`).
