### ISSUE TITLE
How does Kodiak handle signoffs?

### ISSUE THREAD

**Issue by tamalsaha** [chdsbd/kodiak#418]
If I user `squash` merge mode for prs and `body = "pull_request_body"`, does Kodiak will automatically add the sign offs from the prs? Also, recently GitHub started showing `Co-authored-by` commits. Is it possible to support that in Kodiak?

**Comment by chdsbd** [comment]
I think this feature request covers your use case: https://github.com/chdsbd/kodiak/issues/277

As a workaround I think using `"github_default"` for the merge body would give you GitHub's suggested co authors.

**Comment by chdsbd** [comment]
#277 has been resolved so I'm closing this issue. See the docs for information about adding coauthors: https://kodiakhq.com/docs/config-reference#mergemessageinclude_coauthors

Feel free to reopen if this is still an issue.
