### ISSUE TITLE
Rename `blacklist_labels` to `denylist_label`

### ISSUE THREAD

**Issue by tdeekens** [chdsbd/kodiak#437]
## Description

The config of Kodiak allows to specify various blacklist types. 

## Solution

I would propose to rename any occurance of blacklist to allowlist to avoid oppressive wording. 

These include:

1. `blacklist_labels`
2. `blacklist_title_regex`
3. `blacklist_usernames`

which can be renamed to

1. `denylist_labels`
2. `denylist_title_regex`
3. `denylist_usernames`

I would propose to perform this in a backwards compatible way so the old blacklist configs continue to work while they are not documented anymore and a part of the documentation informs about the possible migration.

**Comment by chdsbd** [comment]
Here's what I came up with:

Before
```
merge.blacklist_title_regex
merge.blacklist_labels
update.blacklist_usernames
```

After
```
merge.blocking_title_regex
merge.blocking_labels
update.ignored_usernames
```

I think we can update the documentation for the old terms to say "Deprecated. Please see `merge.blocking_title_regex` for documentation".

**Comment by tdeekens** [comment]
I agree. Blocking labels as a naming is even more clear. To me I would support both and add a deprecation notice to the blacklist wording, yes.
