### ISSUE TITLE
`merge.optimistic_updates` documentation unclear

### ISSUE THREAD

**Issue by MrBartusek** [chdsbd/kodiak#446]
Config references feature [merge.optimistic_updates](https://kodiakhq.com/docs/config-reference#mergeoptimistic_updates)

---

### `merge.optimistic_updates`
- type: `boolean`
- default: `true`

Don't wait for in-progress status checks on a PR to finish before updating the branch.

This setting can speed up merges but increases chance of running extra CI jobs.

---

As new Kodiak, I don't really understand that setting

- what is `wait for in-progress status checks`. Don't all status check are work-in-progress when pr is created?
- `but increases chance of running extra CI jobs.` extra CI jobs when? I don't think there is *chance* to run extra check when something is merged
- I was looking for an option that will ensure that all status checks pass before merging, idk if it is it, the option is really confusing

**Affected file**
[config-reference.md](https://github.com/chdsbd/kodiak/blob/master/docs/docs/config-reference.md#mergeoptimistic_updates)

**Comment by chdsbd** [comment]
If you open a pull request that is out of date with the target branch, and you have the "Requires branches to be up to date" Branch Protection setting enabled, you must update the pull request before it can be merged.

With `merge.optimistic_updates = false`, Kodiak waits for any running status checks to finish before updating the pull request branch. With `merge.optimistic_updates = true`, Kodiak will update the pull request if needed without waiting for those in-progress status checks to finish.

Kodiak is driven by GitHub Branch Protection settings. If you want to ensure that all status checks pass before merging, please mark those status checks as required by GitHub Branch Protection settings.

**Comment by MrBartusek** [comment]
@chdsbd Thanks! Now I know everything! Is it possible to add that information to docs?

**Comment by chdsbd** [comment]
I'll look at improving the docs for this configuration option.

You may also want to checkout https://kodiakhq.com/docs/features, which should hopefully be easier to read than the configuration reference.
