### ISSUE TITLE
Override some config keys for certain PRs

### ISSUE THREAD

**Issue by staabm** [chdsbd/kodiak#476]
We usually use  the „squash and merge“ strategy to merge feature PRs into the target branches. Therefore we configured kodiak for this use case in the kodiak config  file.

Still we have a need to merge some PRs with „merge by merge-commit“ strategy (e.g. when merging commits between release branches). We do this atm via manually pushing the green button.

It would  be great if it would be possible to override certain config keys for some PRs.. 
I could think of e.g. PR label named `kodiak.merge.method:merge` which overrides only the merge-method. Maybe there are other means which could work, too?

 I will leave this here for further discussion..

**Comment by staabm** [comment]
another approach could be:


Define different "config-sets" in the config file and depending on the merge label, kodiak could use different configurations

**Comment by chdsbd** [comment]
Do you see any other keys needing to be overridden for certain PRs?

I think your label suggestion is probably easier to implement than the config option, but I'm open to suggestions if you have ideas about how the config option would look.

For the label solution we already have labels in the `mergeable` function and would only need to update this `get_merge_method` function to accept and use labels for determining the merge method.

https://github.com/chdsbd/kodiak/blob/dcb31e21b1dc89cc14daf81cb97c896a3d49b21d/bot/kodiak/evaluation.py#L356-L377

**Comment by staabm** [comment]
atm I can only think of the merge-method

**Comment by chdsbd** [comment]
#501 has been deployed. I haven't added documentation yet, but you can now override `merge.method` with a pull request label (`kodiak:merge.method='rebase'`).

The label is basically the `.toml` config prefixed by `kodiak`, so it can be formatted in a few ways and will have the same effect: `kodiak:merge.method='squash'`, `kodiak: merge.method = "merge"`.

Let me know if you have any trouble.

**Comment by chdsbd** [comment]
If anyone wants to override more config keys we can open another issue.

**Comment by clxmstaab** [comment]
@chdsbd would it be possible to combine the merge-method label, with a automerge label?

we would want to only add a single label to a PR to make the merge happen.

as it stands today, we need to set one label to override the merge-method and another one to start the automerge itself.

I guess a possible solution could be to allow multiple merge-labels, so we could set `kodiak:merge.method='squash'` additionally as a merge label

**Comment by chdsbd** [comment]
@clxmstaab I like your idea of allowing multiple automerge labels. Maybe we can add a new field, merge.automerge_labels, that would be a list of labels. Or maybe allow specifying a list of labels with merge.automerge_label, although it seems weird since that config setting isn't plural.
