### ISSUE TITLE
Tag not replicated in Docker hub after release v0.20.0

### ISSUE THREAD

**Issue by etiennetremel** [chdsbd/kodiak#493]
It seems that Git tags aren't correctly pushed to Docker hub. The last available tag is v0.20.0.
Still, I can use the commit sha but having back the tag there would be better for user experience.
Anything I can help with to get the tag available there as well as in git?

**Comment by chdsbd** [comment]
I think we need to update the `.circleci/config.yml` to build tags.

https://circleci.com/docs/2.0/configuration-reference/#tags
