### ISSUE TITLE
Title gets chopped up when merging

### ISSUE THREAD

**Issue by Nikamura** [chdsbd/kodiak#496]
We are using kodiak with these settings

```
version = 1

[merge]
automerge_label = "automerge"
blocking_labels = ["wip"]
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title" 
body = "pull_request_body"
strip_html_comments = true  
include_pull_request_url = true
include_pr_number = false
```

but when Pull Request is merged and title is long it chops it up into "Begining of the sen..." and puts rest of the text in body. 
Can this behaviour be customized so it will merge PR with whatever title is of the PR without these mods?

**Comment by chdsbd** [comment]
I was able to reproduce this issue with the following title:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In posuere lorem justo, nec ullamcorper magna sagittis sed. Morbi ac lorem sit amet tortor fringilla condimentum sed ut ligula. Curabitur eget justo porta, bibendum felis ac, blandit nibh. Suspendisse ut est et nunc interdum vehicula sed quis erat
```

<img width="675" alt="image" src="https://user-images.githubusercontent.com/1929960/90801826-6568a880-e2e4-11ea-8bee-bc31cc215aec.png">

I think this is just how the GitHub UI displays long commit titles. Looking in `git` the commit title was not split into multiple lines.


Here's the commit copied from `git log`
```
commit d82c261f89c020bd8833c07b245d2c7645d26e60 (HEAD -> master, origin/master, origin/HEAD)
Author: Christopher Dignam
Date:   Thu Aug 20 12:54:04 2020 -0400

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In posuere lorem justo, nec ullamcorper magna sagittis sed. Morbi ac lorem sit amet tortor fringilla condimentum sed ut ligula. Curabitur eget justo porta, bibendum felis ac, blandit nibh. Suspendisse ut est et nunc interdum vehicula sed quis erat (#32)
    
    hello world 123123
    
    abc
    123123
```

**Comment by chdsbd** [comment]
I think this is resolved. If not, feel free to reopen the issue.
