### ISSUE TITLE
Different merge methods for different branches

### ISSUE THREAD

**Issue by mihai-cindea** [chdsbd/kodiak#497]
I looked over the docs and couldn't find anything, but please correct me if it already exists:
Example: use `squash` for branch name `develop`, but for `master` branch always use `merge` ?
Use case: We have a `develop` branch where all the features get merged and we want them squashed, but when we merge `develop` into `master` it would be nice to have a merge so we preserve all the history.

**Comment by chdsbd** [comment]
You're correct, Kodiak doesn't support per branch configuration. We need new configuration options to support your desired use case.

Would https://github.com/chdsbd/kodiak/issues/476 work for your use case?

Maybe we could do something like the following for the configuration. We could add a new `branch_override` key and allow overriding configuration settings per branch.

```toml
[branch_override."my-branch-name-here".merge]
method = "merge"
```

I'm curious if you have ideas for what the configuration in the `.kodiak.toml` would look like.

**Comment by mihai-cindea** [comment]
Yes! actually the tag idea would be much better, since that way I can only add that tag to a specific branch after i checked that the source branch is actually `develop` in my case, otherwise it would require an extra config like "source_branch".
The tag idea also it adds more flexibility going forward.
Thanks for the fast response!

**Comment by chdsbd** [comment]
@mihai-cindea It's now possible to override `merge.method` for specific PRs with a label (`kodiak: merge.method = "rebase"`). This comment has more information: https://github.com/chdsbd/kodiak/issues/476#issuecomment-687658106

Let me know if this solves your issue.

**Comment by mihai-cindea** [comment]
Oh, wow @chdsbd I didn't expect you to work on this so fast, I ended up writing a custom github action bot. While I can't confirm it works for me I assume it would have, and will close this issue.
Thank you so much for the fast response!
