### ISSUE TITLE
update.always

### ISSUE THREAD

**Issue by Norfeldt** [chdsbd/kodiak#505]
This looks like an awesome bot. I'm giving it a try and going through the settings.

I have a question about the [update.always](
https://kodiakhq.com/docs/config-reference#updatealways) setting. 

Say I have two branches with the 'automerge' and 'dependency' labels. One of them passes the tests first, Kodiak merge it in. Then the other one is behind.

Will Kodiak detect that (with `update.always = true`) and do a rebase (and push it to the PR) on the branch behind?

**Comment by chdsbd** [comment]
By default, `update.always` will update the second PR so it's even with the target branch, when the "Require branches to be up to date before merging" branch protection setting enabled.

I'm assuming you're using Dependabot based on the `dependency` label, in which case you'll probably want to disable `update.always` and let Dependabot handle updating the pull requests.

https://kodiakhq.com/docs/recipes#adding-pull-request-approvals-to-dependabot-pull-requests

So your config would look something like this:
```toml
[update]
always = true
ignored_usernames = ["dependabot"]
```

Let me know if you have any more questions.

**Comment by Norfeldt** [comment]
Thank you very much for replying so quickly.

> By default, update.always will update the second PR so it's even with the target branch, when the "Require branches to be up to date before merging" branch protection setting enabled.

Does this means that this settings is only relevant for Enterprise Github accounts that has the **"Require branches to be up to date before merging"** branch protection setting _enabled_

**Comment by chdsbd** [comment]
`update.always` is relevant when the "Require branches to be up to date before merging" branch protection setting enabled. Branch protection is available for all public repositories as well as private repositories of paid GitHub accounts.

**Comment by Norfeldt** [comment]
Thank you, Christopher Dignam
