### ISSUE TITLE
Skipped check doesn't count as failure

### ISSUE THREAD

**Issue by sindrig** [chdsbd/kodiak#508]
We're reviewing Kodiak for our monorepo. Straight away it seems that Kodiak merged a PR that should not have been mergeable.

https://github.com/island-is/island.is/pull/1061

We require the `success` step to be successful but it wasn't. Is there any extra configuration we need to do? Also, shouldn't this have been fixed by https://github.com/chdsbd/kodiak/pull/352?

**Comment by chdsbd** [comment]
Hi @sindrig,

Sorry about the unexpected merge.

Kodiak obeys GitHub Branch Protection settings. So if you want Kodiak to wait for a certain status checks you need to mark them as "Required" in GitHub Branch Protection settings.

For Kodiak's repository the settings look like this:
<img width="800" alt="Screen Shot 2020-09-24 at 1 31 32 PM" src="https://user-images.githubusercontent.com/1929960/94179277-48d30980-fe6a-11ea-80d2-3905d5b7fe4a.png">


Hope this helps. Let me know if you have any questions.

Thanks,
Chris

**Comment by sindrig** [comment]
Wow, you're right. I thought skipped checks would count as failures. Is it possible to configure kodiak to count skipped checks as failed?

You can see a simpler test of this here: https://github.com/sindrig/kodiaktest/pull/8

Basically I've got a before step that always fails, and a run step that's required and it `needs` before. Could I be doing something else?

**Comment by sindrig** [comment]
I think I've got it - it's just a matter of putting `if: always()` in the final step as seen in https://github.com/sindrig/kodiaktest/pull/8/commits/1dbf2029e934442a317aa3d3a41110e87cb7507f

I'm going to keep this issue open until I verify it in island-is/island.is if that's okay :)

**Comment by sindrig** [comment]
Looks like it works as promised, sorry for the noise and thanks for this great tool :tada:
