### ISSUE TITLE
Feature Request: An auto-update label to allow selective auto-update without auto-merge

### ISSUE THREAD

**Issue by mattjw** [chdsbd/kodiak#529]
## Limitation

Looking through the [config](https://kodiakhq.com/docs/config-reference), if a developer wants to use auto-update, they have two options:

- Auto-update is enabled for all PRs
- Auto-update is enabled for all PRs that opt in to auto-merge

From the docs:

> Kodiak will only update PRs with the merge.automerge_label label or if update.require_automerge_label = false.

For my use case, it would be great to have a third option:

- Auto-update is enabled for all PRs that opt in to auto-update

## Feature request

This opt-in could be implemented via another label such as `auto-update`. As a bonus it would be great to make the label name configurable, just like Kodiak does for auto-merge via `merge.automerge_label`.

It goal is that a developer can choose to opt-in to auto-update on a given PR without opting in to auto-merge.

## Background

We're looking to move off a Bulldozer-managed auto-update and auto-merge, since we've discovered that it doesn't support auto-update of PRs from forks. Also, aside from wanting to overcome that limitation, another reason to move over is because Kodiak as a whole looks awesome 💯. Ideally we'd want to replicate the opt-in-to-auto-update functionality from Bulldozer, which is what motivated this Feature Request.

**Comment by chdsbd** [comment]
Thanks for the detailed feature request.

By default Kodiak is efficient when merging pull requests and only updates them before merge, if necessary. When `update.always = true` Kodiak will immediately update any pull request that becomes out of date with the target branch.

From what I understand, you'd like the behavior of `update.always = true`, but only when a specific label is applied to a pull request. Is that correct?

Maybe the new config option could be `update.autoupdate_label`.

This should be a relatively small change. We'd need to add a new config option:
https://github.com/chdsbd/kodiak/blob/cff9897dbe02fb638e5bc416c29d416d746fc79e/bot/kodiak/config.py#L103-L113

And then modify the pull request update logic to use this field:

https://github.com/chdsbd/kodiak/blob/cff9897dbe02fb638e5bc416c29d416d746fc79e/bot/kodiak/evaluation.py#L631-L636

**Comment by mattjw** [comment]
Thank you for having a look at this request.

> From what I understand, you'd like the behavior of update.always = true, but only when a specific label is applied to a pull request. Is that correct?

That's right 👍.

> Maybe the new config option could be `update.autoupdate_label`.

`autoupdate_label` is exactly the config I was looking for when reading through the [reference](https://kodiakhq.com/docs/config-reference). I saw `merge.automerge_label` and was hoping to find the auto-update counterpart.

Maybe the semantics of having options `update.always=True` and `update.autoupdate_label = "blabla"` could be a little confusing at first, but solvable with documentation?

I was wondering about a `update.require_autoupdate_label` but in the end that felt even more confusing.

**Comment by chdsbd** [comment]
[`update.autoupdate_label`](https://kodiakhq.com/docs/config-reference#updateautoupdate_label) is now available. Let me know if you have any issues.

**Comment by mattjw** [comment]
Thank you @chdsbd! 🙇 This opens the path to trying Kodiak here. Will be in touch if we do hit any trouble.
