### ISSUE TITLE
Kodiak has suddenly stopped working

### ISSUE THREAD

**Issue by gnarea** [chdsbd/kodiak#535]
Hi,

I can't figure why Kodiak has suddenly stopped working across all repos in my organisation. Here's an example: https://github.com/relaycorp/relaynet-poweb-js/pull/38

Kodiak approved the PR 17 hours ago and I added the `automerge` label 2 hours ago, but Kodiak isn't showing up in the PR checks.

Cheers.

**Comment by chdsbd** [comment]
Hi @gnarea,

Sorry about that. Based on uptime checks, Kodiak was down from `2020-10-17 02:35:24 UTC-4` to `2020-10-17 08:05:21 UTC-4`. I changed my hosting setup on Thursday and I made a mistake that allowed this to happen.

I'm working to prevent this from happening again.

**Comment by gnarea** [comment]
Thanks @chdsbd! No worries at all. Glad it's back up.

I'm leaving this issue open in case you're using it to track any remaining work, but feel free to close it if it's done now.
