### ISSUE TITLE
ignored_usernames only working when update.always === true

### ISSUE THREAD

**Issue by pheew** [chdsbd/kodiak#537]
In general kodiak works great so thanks for creating it 👍 

On our pretty large repo we use renovate to create PRs for dependency management. We also have a branch policy in place to force branches to always be up-to-date before merging. This is to prevent issues with lockfiles getting out of sync.

The problem we face is that, as soon as kodiak updates a renovate PR, renovate will no longer update it as it sees 'external' change made on the branch.

Currently we use `ignored_usernames` to always blacklist these PRs from being updated by kodiak. The problem is that the only way to do that is to set `update.always` to `true`. When there's lots of PRs ready to be merged this leads to congestion on our CI pipelines. 

Would it be possible to change the behavior of `ignored_usernames` to always respect that setting even if `update.always` is not set to `true`? Because then kodiak would keep efficiently merging the queued PRs and leave updating the renovate PRs to renovate.

(Somewhat related to #505 but feel this needed separate discussion)

**Comment by chdsbd** [comment]
Would turning off `update.always` work for your use case?

When `update.always` is disabled Kodiak will only update a branch just before it merges the pull request, so you shouldn't see any conflicts with Renovate.

**Comment by pheew** [comment]
Ideally would actually like to disable `update.always` but the trouble with that is that also disables `ignored_usernames` which means Kodiak will start updating renovate PRs as well.

So our problem really boils down to the `ignored_usernames` only working when `update.always` is enabled

**Comment by pheew** [comment]
Just be clear, you're right in that it will work. But we need be careful with adding the `merge` label one by one.

**Comment by chdsbd** [comment]
I think I understand.

If Renovate PRs are out-of-date with their target branches, Kodiak should skip them and let Renovate update them later.

Currently if you let Kodiak update the Renovate PRs, the first one will merge, but the following ones will get conflicts and Renovate won't fix them if they've been updated by Kodiak.

Is that all correct?

Out of curiosity, do you know how long it takes for Renovate to update the out-of-date PRs? I wonder how long it would take a chain of four Renovate PRs to be merged in if Renovate was the only one to update them.

**Comment by chdsbd** [comment]
I think changing the behavior of `update.ignored_usernames` would be a backwards incompatible change. So I think we need to add a new config option, like `update.never_update_ignored_usernames`, which would make it so Kodiak would skip `update.ignored_usernames` when merging a PR.

**Comment by pheew** [comment]
> I think I understand.
> 
> If Renovate PRs are out-of-date with their target branches, Kodiak should skip them and let Renovate update them later.
> 
> Currently if you let Kodiak update the Renovate PRs, the first one will merge, but the following ones will get conflicts and Renovate won't fix them if they've been updated by Kodiak.
> 
> Is that all correct?

Yeah exactly right 👍 

> Out of curiosity, do you know how long it takes for Renovate to update the out-of-date PRs? I wonder how long it would take a chain of four Renovate PRs to be merged in if Renovate was the only one to update them.
> 
> EDIT: I checked the docs and they don't give a timeframe on when Renovate will rebase the branches [docs.renovatebot.com/updating-rebasing/#rebasing-out-of-date-branches](https://docs.renovatebot.com/updating-rebasing/#rebasing-out-of-date-branches)

It responds to merges to the base branch and updates on the PR using GitHub hooks just like kodiak so the turn around time is quite short. It isn't very smart about determining priority so it will just update all pending dependency PRs though.


> I think changing the behavior of `update.ignored_usernames` would be a backwards incompatible change. So I think we need to add a new config option, like `update.never_update_ignored_usernames`, which would make it so Kodiak would skip `update.ignored_usernames` when merging a PR.

Currently it seems the defined behavior of a set `update.ignored_usernames` without `update.always` being `true` is that the `update.ignored_usernames` is ignored. I guess strictly speaking that would be breaking but in practice it shouldn't be a huge deal right? But I might very well be missing something ofcourse.

**Comment by hugo** [comment]
This is also an issue for Dependabot updates, and I would be equally interested in a solution. Dependabot is (sometimes) much slower at updating PRs than it sounds like Renovate is, so this is a frequent issue for my team.

**Comment by chdsbd** [comment]
Thanks for the report @hugo.

I'll try to get a fix out for this by next week.

@pheew I think you're right that it's okay to change `update.ignored_usernames` without adding another flag. That config option was added specifically for Dependabot updates anyway.

**Comment by hugo** [comment]
Appreciate you jumping on this so fast, @chdsbd. Very happy to know I should soon never have to write another `@dependabot recreate` comment again 😄.

**Comment by chdsbd** [comment]
#544 has been released to resolve this issue.

Now when a pull request's author matches `update.ignored_usernames`, Kodiak will never update the pull request, unless `update.autoupdate_label` is applied to the pull request.
