### ISSUE TITLE
How to improve performance for self-hosted Kodiak

### ISSUE THREAD

**Issue by etiennetremel** [chdsbd/kodiak#545]
Thanks again for this amazing tool. We are using it intensively in our organization and for this reason we decided to use the host it ourselves.

The [self-hosting page](https://kodiakhq.com/docs/self-hosting) doesn't mention anything about high availability. Kodiak react on Github events via webhook so Kodiak should run at least on 2 instances if we don't want to miss any events.

When an event is received, Kodiak add it to a Redis queue and prioritise it somehow? How does that work?

When it get really busy, I noticed quite a slow down in the response after adding the merge label, it can take few hours and sometimes it is just hanging. We need to manually remove and add the label again to have it merged. Is that something you also experience?

**Comment by chdsbd** [comment]
Kodiak is limited to 1 request per second to the GitHub API, so if you have a lot of activity it may take Kodiak some time (minutes) to catch up.

Kodiak does not support running multiple instances. GitHub sends enough webhook requests that it's usually okay if Kodiak misses a few events. 

A slowdown of a few hours is _not_ expected. My guess is there's some error Kodiak is hitting and it's just luck that GitHub sends another webhook event for the affected pull requests.

Do you have Sentry setup for your Kodiak instance? That would help pinpoint any errors.

**Comment by etiennetremel** [comment]
Thanks for the quick reply and explanation, we don't have Sentry setup yet, I will look into it.

From time to time we are seeing the following timeouts in the logs:
```
INFO kodiak.pull_request:pull_request.py:304 event='queue_for_merge' install='8601422' number=367 owner='my-org' repo='my-repo'
INFO kodiak.queue:queue.py:298 event='enqueue repo event' install='8601422' number=367 owner='my-org' repo='my-repo'
INFO kodiak.queue:queue.py:244 event='task failed'
INFO kodiak.queue:queue.py:247 event='exception' excep=TimeoutError()
INFO kodiak.queue:queue.py:249 event='creating task for queue'
INFO kodiak.queue:queue.py:178 event='start repo_consumer' queue='merge_queue:8601422.my-org/my-repo'
INFO kodiak.queue:queue.py:126 event='block for new repo event' queue='merge_queue:8601422.my-org/my-repo'
INFO kodiak.evaluation:evaluation.py:969 event='not setting status message for enqueued job because is_active_merge=True' number=367 url='https://github.com/my-org/my-repo'
INFO kodiak.pull_request:pull_request.py:118 event='evaluate_pr successful' install='8601422' number=367 owner='my-org' repo='my-repo'
INFO kodiak.queue:queue.py:59 event='block for new webhook event' queue='webhook:8601422'
INFO kodiak.queue:queue.py:61 event='parsing webhook event' queue='webhook:8601422'
INFO kodiak.queue:queue.py:83 event='evaluate pr for webhook event' queue='webhook:8601422'
```
Can this be a pointer?

**Comment by etiennetremel** [comment]
Is Sentry only available on the webui? I only see `SENTRY_DSN` available there. I'm using the bot image: `cdignam/kodiak`

**Comment by etiennetremel** [comment]
Thanks @sbdchd , I added Sentry earlier this week and I can see few different type of events but the one that is a bit more outstanding is this one:

```
TimeoutError: null
  File "kodiak/queue.py", line 180, in repo_queue_consumer
    await process_repo_queue(log, connection, queue_name)
  File "kodiak/queue.py", line 159, in process_repo_queue
    queue_for_merge_callback=queue_for_merge,
  File "kodiak/pull_request.py", line 86, in evaluate_pr
    timeout=10,
  File "asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
```

**Comment by sbdchd** [comment]
I think you must be on an old version because the timeouts in `kodiak/pull_request.py` are at 30 seconds instead of 10.

Possibly related: https://github.com/chdsbd/kodiak/commit/c7b7a393b1395b90b9464fcf4626867415e20711

**Comment by etiennetremel** [comment]
Rightly spotted, I was using an old version from the 6th of July d9708b0. Oops 🙈 
I will keep it running for a bit and see how that goes. Meanwhile, I will close this issue and re-open if we notice any weird behavior.

Thanks all for taking the time to help!

**Comment by chdsbd** [comment]
@etiennetremel If you haven't already done so, you may want to subscribe to release notifications on this repository, so you can get bug fixes and avoid issues with GitHub API changes.

https://docs.github.com/en/enterprise-server@2.20/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository#watching-releases-for-a-repository
