### ISSUE TITLE
Helm chart for bot deployment

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [chdsbd/kodiak#551]
I was looking to create a Helm chart for deployment of kodiak on some Kubernetes infrastructure we have. Would you accept such a chart in a PR to this repo? I'd love to give back, OTOH I could understand not wanting to bring that in-tree.

**Comment by sbdchd** [comment]
There are some existing Helm charts floating around like: https://github.com/FikaWorks/helm-charts/tree/e02529d592fc4572aa156718811140a94b3e6d2f/charts/kodiak

I think it would be better to link to your helm chart in the self-hosting docs, as we don't use Helm so it would probably atrophy in the repo itself.

**Comment by mariadb-JeffBachtel** [comment]
FikaWorks's chart looks good, I'll add docs to self-hosting and link to it, if you think that'd be okay. Thanks for the response

**Comment by sbdchd** [comment]
yup that works for me
