### ISSUE TITLE
add additional conditional to approve.auto_approve_usernames

### ISSUE THREAD

**Issue by haghabozorgi** [chdsbd/kodiak#554]
Currently kodiak supports `approve.auto_approve_usernames`.

It would be nice if there were some additional conditional like a label (e.g `approve.auto_approve_labels`) to allow some further customization. If you are using a single github 'bot user' account for example for more than one automation task, you might want to have some of the bot users PRs auto-approved, and other PRs not. If they are both set then both conditions must be met before auto-approval. This could possibly also allow auto-approval based on just a label as opposed to a user as well.

**Comment by chdsbd** [comment]
Interesting idea. I think the implementation would be similar to `approve.auto_approve_usernames`.

https://github.com/chdsbd/kodiak/blob/ec209b151b8a4dc4c9b0c36ae5cb12d9419feb52/bot/kodiak/evaluation.py#L606-L621

We'd need to add a new configuration option and update the logic in `evaluation.py`.

I think `approve.auto_approve_labels` and `approve.auto_approve_usernames` being separate such that one doesn't require the other would match the behavior of other configuration options in Kodiak.
