### ISSUE TITLE
Queue positions per target branch

### ISSUE THREAD

**Issue by staabm** [chdsbd/kodiak#556]
We see unnecessary queueing of merges, which lead to wait-times.
In our case it’s unnecessary because we see PR B and PR C wait for PR A, even though B and C have a different target branch then A.
Even when all checks on PR B and C are green, they still wait for PR A (which in our case takes 30-45 minutes longer to complete its checks)

Wouldn‘t it make sense to use separate queues per target branch?

Our config: https://raw.githubusercontent.com/redaxo/redaxo/master/.github/.kodiak.toml

**Comment by chdsbd** [comment]
You're right, there's only one merge queue. It definitely makes more sense to have a queue per target branch.

This is where we currently queue pull requests.
https://github.com/chdsbd/kodiak/blob/ec209b151b8a4dc4c9b0c36ae5cb12d9419feb52/bot/kodiak/queue.py#L273-L290

I'm not 100% certain, but I think if we update this function to return a queue name based on the target branch, that should give us per-branch queues. We'd need to lookup the target branch for the pull request to make this work.

https://github.com/chdsbd/kodiak/blob/ec209b151b8a4dc4c9b0c36ae5cb12d9419feb52/bot/kodiak/queue.py#L308-L309

**Comment by chdsbd** [comment]
#572 has been deployed which should resolve this issue. Let me know if you run into any issues.
