### ISSUE TITLE
Exclude kodiak and other merge users from co-authors

### ISSUE THREAD

**Issue by gharlan** [chdsbd/kodiak#576]
It seems that if kodiak has updated a pr and if `include_coauthors` is activated, kodiak becomes a co-author. [Example](https://github.com/redaxo/redaxo/commit/3fae54984677b32368d4008069af9a9a402620ff)
I think it should be excluded from the co-author list.

Or maybe exclude all `[bot]` users?

**Comment by gharlan** [comment]
Or maybe exclude all merge commits?
If I click on the "Update branch" button on github, I become the author of the merge commit.
I have not tested it, but I suspect that I would become a co-author then, too.

**Comment by gharlan** [comment]
> I have not tested it, but I suspect that I would become a co-author then, too.

I have tested it now, and yes, the user who clicked `Updated branch` in a pr, becomes a co-author.

**Comment by chdsbd** [comment]
Excluding Kodiak from coauthors should be a simple change. We'd need to update this code to exclude Kodiak.
https://github.com/chdsbd/kodiak/blob/871cf119cd888dd7bbdf2e763761a53030e5a868/bot/kodiak/evaluation.py#L172-L178

It seems like filtering out all merge commits is a little more complicated. One solution I think is to fetch `parents.totalCount` for each commit and exclude commits with more than one parent.


Commit API object: https://docs.github.com/en/free-pro-team@latest/graphql/reference/objects#commit

**Comment by chdsbd** [comment]
#581 has been deployed which should resolve this issue by ignoring merge commits for coauthors. Let me know if you run into any issues.

**Comment by gharlan** [comment]
Thanks for the quick fixes. 👍
