### ISSUE TITLE
Too many blank lines before co-authors if message body is empty

### ISSUE THREAD

**Issue by gharlan** [chdsbd/kodiak#577]
If the message body is empty (because pr description is empty or `body` is configured as `empty`) there are too many blank lines between title and co-authors.

Example commit message:

```
PR title (#issue)



Co-authored-by: ...
```

**Comment by chdsbd** [comment]
To match [the GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) we add two new lines before the coauthor trailers.

<img width="692" alt="Screen Shot 2020-11-28 at 1 01 07 PM" src="https://user-images.githubusercontent.com/1929960/100522826-ca505c00-3179-11eb-8c69-ca0e14d57fd3.png">

It seems that GitHub adds an extra space between the commit title and body. I think we can fix the issue you've encountered by trimming any extra whitespace on merge.

**Comment by chdsbd** [comment]
#578 has been deployed which should resolve this issue. Let me know if you run into any issues.
