### ISSUE TITLE
kodiak does not work atm

### ISSUE THREAD

**Issue by clxmstaab** [chdsbd/kodiak#585]
are there any known problem with the kodiak bot right now?

it does no longer show up in some of our PRs (which worked before)

**Comment by csprle** [comment]
We have the same issue. At first, I was adding the `automerge` label but Kodiak was still waiting for this label. Now kodiak doesn't show up at all in the GitHub pull request checks.

**Comment by lassesteffen** [comment]
Same here

**Comment by chdsbd** [comment]
Sorry, I'm looking into this now.

**Comment by chdsbd** [comment]
This should be resolved now. I'm working on gradually triggering all installations for revaluation, but you can edit a pull request to trigger Kodiak to run again.

Kodiak was down for 6.5 hours, starting at 2020-12-01 01:32:20 UTC-5 and resolving at 2020-12-01 08:02:17 UTC-5.

I got an alert when Kodiak went down, but I was asleep. I'm going to change the alerting to call me in case of an outage.

**Comment by lassesteffen** [comment]
You are the best 💯

**Comment by clxmstaab** [comment]
can confirm, it works again. thx for fixing.

> I got an alert when Kodiak went down, but I was asleep.

your response time is fast enough for me.. you don't need to interrupt your night for us :).

thx again!

**Comment by csprle** [comment]
> your response time is fast enough for me.. you don't need to interrupt your night for us :).

+1

works again, thanks for solving

**Comment by chdsbd** [comment]
In case anyone is curious, I believe this bug caused the outage this morning: https://bugs.launchpad.net/ubuntu/+source/containerd/+bug/1870514

Apparently an automated security update for containerd triggered a bug that caused Docker to shutdown and not restart.
