### ISSUE TITLE
Unable to bring up development environment because of markdown-html-finder

### ISSUE THREAD

**Issue by scriptnull** [chdsbd/kodiak#588]
Hi, I am trying to bring up a development environment of kodiak in my local machine. But, I keep seeing the following error while running `poetry install` in the bot folder ([as per the instructions here](https://github.com/chdsbd/kodiak/blob/master/bot/README.md)).

I am very new to python ecosystem and thought that I might get help by asking here.

```
$ poetry install 
Installing dependencies from lock file
The "black" dependency specifies the "allows-prereleases" property, which is deprecated. Use "allow-prereleases" instead.
The "black" dependency specifies the "allows-prereleases" property, which is deprecated. Use "allow-prereleases" instead.

Package operations: 1 install, 0 updates, 0 removals

  • Installing markdown-html-finder (0.2.2): Failed

  RuntimeError

  Unable to find installation candidates for markdown-html-finder (0.2.2)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

any idea/fix for tackling this problem?

**Comment by sbdchd** [comment]
Hmm not entirely sure but it might be that we're using a really old version of poetry.

We install it via:

https://github.com/chdsbd/kodiak/blob/3ae989e84653ba26fa901dc3eac5abaf3ad87093/.circleci/config.yml#L27-L29

Also that package in particular is some Python bindings to a Rust library so it needs to be compiled for the [specific operating system and python version](https://pypi.org/project/markdown-html-finder/0.2.2/#files).
Which OS and python version are you using?

**Comment by scriptnull** [comment]
Thanks @sbdchd 

Here is the information about my system.

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ uname -a
Linux scriptnull-XPS-15-9500 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ python3 --version
Python 3.8.5
$ poetry --version 
Poetry version 1.1.4
```

I am going to try removing the dependency and see how it goes.

**Comment by chdsbd** [comment]
This should be fixed now. I published more markdown-html-finder Wheels for Python3.8 and Python3.9 for macOS and Linux.
