### ISSUE TITLE
Self-hosted not working in heroku

### ISSUE THREAD

**Issue by tamalsaha** [chdsbd/kodiak#609]
Thanks for this incredibly useful too. I tried to deploy this in heroku following your instructions. But it does not work. And I am not sure how to debug. One thing I noticed in heorku applications logs is that I seeting lots of `400` status codes like below:

```
2021-01-30T22:52:01.104454+00:00 app[web.1]: INFO uvicorn:httptools_impl.py:436 ('10.52.12.238', 14061) - "POST /api/github/hook HTTP/1.1" 400
2021-01-30T22:52:01.104958+00:00 heroku[router]: at=info method=POST path="/api/github/hook" host=kodiak-appscode.herokuapp.com request_id=1ab16619-028b-4d6d-96ea-669e05382261 fwd="140.82.115.148" dyno=web.1 connect=0ms service=2ms status=400 bytes=190 protocol=https
```

Do you have any ideas/hints on how to debug this?

**Comment by chdsbd** [comment]
My guess is there's a problem with the private key or app ID. You can view web hook API responses in the GitHub UI: 
<img width="954" alt="Screen Shot 2021-01-30 at 6 06 56 PM" src="https://user-images.githubusercontent.com/1929960/106370228-00e75600-6326-11eb-8ccf-04f52156047f.png">


`https://github.com/settings/apps/your-app-name-here/advanced`



I'd also try setting up Sentry and configuring the `SENTRY_DSN` environment variable as mentioned in the docs: https://kodiakhq.com/docs/self-hosting

**Comment by tamalsaha** [comment]
Thanks, @chdsbd . I am seeing `{"detail":"Missing required signature: X-Hub-Signature"}` error in Github webhook logs.

![GitHub-Apps-kodiak-appscode](https://user-images.githubusercontent.com/94814/106370589-4436ca00-6310-11eb-812b-563f99471717.png)

**Comment by chdsbd** [comment]
You need to setup a secret token for the web hook. Kodiak uses the token to verify the authenticity of the web hook requests.

https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks#setting-your-secret-token

<img width="525" alt="Screen Shot 2021-01-30 at 6 40 35 PM" src="https://user-images.githubusercontent.com/1929960/106370714-a8668780-632a-11eb-95dc-b3c2f80f33b5.png">

**Comment by tamalsaha** [comment]
Thank you! It is working now.

**Comment by mutukrish** [comment]
@tamalsaha @chdsbd Could let me know what is environment variable name that needs to be declared in Heroku side for webhook secret?

**Comment by tamalsaha** [comment]
@mutukrish https://kodiakhq.com/docs/self-hosting
