### ISSUE TITLE
UI for currently merging PRs

### ISSUE THREAD

**Issue by scriptnull** [chdsbd/kodiak#621]
https://github.com/chdsbd/kodiak/issues/616 implemented UI for merge queues. While trying to use it, I just realized that it would also be good to show which PRs are being currently merged by kodiak bot in the dashboard UI. I am guessing that each branch can have at most 1 PR in the "currently merging" state. So, we list them just like the merge queue UI.

Currently, we are cycling through various GitHub pull requests one by one to see if the PR contains the following status check in order to figure this out.

![image](https://user-images.githubusercontent.com/4211715/110426211-b5b22700-80cb-11eb-834f-5b4a2e7e21a3.png)

Having this feature would let us easily get to answers like "whose/which PR is being currently merged by kodiak?"

More power to the Kodiak dashboard :rocket: :fire:

**Comment by chdsbd** [comment]
Whoops! Oversight on my part. This shouldn't be too hard to add.

**Comment by chdsbd** [comment]
This should be fixed with #632. See my comment in #623 for an example of this change: https://github.com/chdsbd/kodiak/issues/623#issuecomment-803684612
