### ISSUE TITLE
Re-run actions failed due to GitHub API Rate limiting

### ISSUE THREAD

**Issue by Aerendir** [chdsbd/kodiak#630]
I don't know if this is something that Kodiak can or would accomplish, but it would be useful to have the ability to re-run actions failed due to GitHub API rate limiting.

I wrote a detailed post here: https://github.community/t/how-to-avoid-api-rate-limiting/168958

I report here for completeness:

I’m using Dependabot and my packages have some continuous integration checks that I run on each PR.

Unfortunately, it often happen that my actions reach the API rate limit.

To mitigate the issue, I’ve implemented a cache to store dependencies and this improved a bit the issue, but not solved it at all.

Is there a way to increase the API limit or, on the other side, retry the failed jobs due to the API limit?

Currently I have over 90 PRs opened and the reason for them to fail is the reach of the limit and so I have to rerun them and this requires a lot of time, also because I have to keep attention to not reach the limit again.

This also causes issues as if I have to upgrade dependencies locally, I anyway have the limit reached and so I have to stop development, waiting for the limit to reset.

They are open source packages for the most part.

**Comment by chdsbd** [comment]
I'm not sure Kodiak can help here. How can Kodiak know if a GitHub Action has encountered a rate limit? And how would Kodiak know when it's safe to retry that Action? Also, is there an API a GitHub App like Kodiak could use to interact with GitHub Actions?

Let me know if you have any ideas, but I think this is out of scope for Kodiak. I haven't had any issues with CircleCI, so that might be worth investigating.

**Comment by Aerendir** [comment]
@chdsbd , unfortunately I have no answers for your questions: I cannot develop an app like Kodiak, nor have the background to find a possible solution.

I simply thought at Kodiak as a possible implementer.

In theory, it would be sufficient to read the log output to understand if the action failed due to the API limits... But I don't know how to read the log output :(

Anyway, thank you for your reply :)

Kodiak is one of the best apps for GitHub and I will continue to use it anyway 💪
