### ISSUE TITLE
kodiak thinks required check failed so it does not merge PR even though the check has passed

### ISSUE THREAD

**Issue by haghabozorgi** [chdsbd/kodiak#640]
We have been using kodibot for over a year self-hosted and recently the bot seems to not merge a large number of our PRs. The bot will complain that a specific check failed but it actually succeeded according to circleci and github. The bot seems to not detect the check properly? 

Workflow:
PR issued against master
author requests reviewer
reviewer approves, 
PR author adds automerge label
checks run, all show passing in github but bot shows cannot merge due to one of the check having failed
some other PR gets merged to master
update branch does not happen automatically here (manually click 'update branch') on the PR
checks re-run, all show passing again in github but bot shows cannot merge due to same check having failed
if we remove the automerge label, and re-add the label, the bot seems to then do the right thing and merge the PR.

![Screenshot_20210325_105003](https://user-images.githubusercontent.com/1186748/112519796-f2cb1a00-8d57-11eb-9a55-b6c11c5be871.png)

![Screenshot_20210325_105147](https://user-images.githubusercontent.com/1186748/112520073-4473a480-8d58-11eb-96a7-693318df8624.png)

**Comment by chdsbd** [comment]
Hi @haghabozorgi,

What version of Kodiak are you running? Do you have Sentry configured and are there any errors reported there?

Kodiak only evaluates and updates the GitHub Status Check when the pull request is modified. It seems like Kodiak failed to evaluate this PR at some point.

Can you reproduce this issue with the Kodiak GitHub Marketplace app?

**Comment by haghabozorgi** [comment]
We are running cdignam/kodiak:v0.38.0. 
We do not use sentry :(
I will have to test with the marketplace version when I have some time, but I see that we were missing the `push` and `status` events subscriptions. I have enabled them and will report back what I find. Thank you @chdsbd  as always for your help.

**Comment by haghabozorgi** [comment]
Thanks again for all your help @chdsbd, always appreciated. The missing events subscriptions did the trick. closing this issue.
