### ISSUE TITLE
Enable repo discussions

### ISSUE THREAD

**Issue by gitfool** [chdsbd/kodiak#646]
I've looked through the references in [Prior Art / Alternatives](https://kodiakhq.com/docs/prior-art-and-alternatives), which was very interesting and helpful, thanks! Some of it seems outdated, in particular wrt [Mergify](https://github.com/Mergifyio/mergify-engine), but initial impressions are that Kodiak looks good. 😉 

Anyway, I'd like to suggest you enable repo discussions to provide a forum for questions and answers.

**Comment by chdsbd** [comment]
Thanks for the suggestion on Discussions, I've enabled them now.

Let me know if you have suggestions for the Prior Art page.
