### ISSUE TITLE
No Kodiak merges today

### ISSUE THREAD

**Issue by l0b0** [chdsbd/kodiak#675]
I'm working on a project which has been using this excellent product for some months now. Some time between [three days ago](https://github.com/linz/geostore/pull/814)  and [an hour ago](https://github.com/linz/geostore/pull/815) it seems to have stopped doing anything with the repository. I wasn't able to find a status page; could you please have a look?

**Comment by chdsbd** [comment]
Whoops. I can confirm. This must be related to the most recent release.

**Comment by chdsbd** [comment]
Sorry about that. I've reverted to an older commit. If you make a change to your affected PR Kodiak will evaluate it again.
