### ISSUE TITLE
Can Kodiak work without config file in the repo?

### ISSUE THREAD

**Issue by okainov** [chdsbd/kodiak#703]
We'd like to use the tool internally for ~50 different repositories and we'd prefer to configure Kodiak once on the server side and do not modify repositories. Would it be possible?

**Comment by sbdchd** [comment]
Currently there isn't anything, but if you're going the self hosting route we could probably add an env var as a hack to support a global config, something like: `DEFAULT_KODIAK_CONFIG_TOML`

https://github.com/chdsbd/kodiak/blob/50ae03014f43c06dab1bd81cfd6825a4aea6fc6a/bot/kodiak/queries/__init__.py#L882-L887

Could update that to check the env var and use that if set ^

**Comment by sbdchd** [comment]
Found a related issue from a while back: https://github.com/chdsbd/kodiak/issues/403

**Comment by erezrokah** [comment]
Also related - when you install the Renovate bot app on a repo, and that repo doesn't have a configuration file, renovate will open a PR with a default configuration.
You can close the PR or merge it to disable/enable the bot.
