### ISSUE TITLE
Kodiak not triggered on forked repo

### ISSUE THREAD

**Issue by KATT** [chdsbd/kodiak#707]
Hey!

First of all - thanks for kodiak - it's amazing. 🙏 

Overall works great for many private and public repos that I've created over the last few years.

Got one repo now though where it's not working - https://github.com/KATT/typescript.careers. Might be because it's a fork(?).

As you can see from the history of my [toml file](https://github.com/KATT/typescript.careers/blob/main/.kodiak.toml) I've had a few stabs at kicking it until the bot wakes up, but it hasn't yet.

Currently, the toml file is identical to one on my [other repo](https://github.com/trpc/trpc/blob/main/.kodiak.toml) and it's doing a terrific job there.

Unsure how to troubleshoot - I don't see where to find any status/reason on why kodiak is not triggering.

Thanks 🙏

**Comment by chdsbd** [comment]
Can you try editing the PR title, body, or labels of this PR https://github.com/KATT/typescript.careers/pull/25 and see if Kodiak picks up your PR?

https://kodiakhq.com/docs/troubleshooting#workarounds

**Comment by chdsbd** [comment]
Hmm, very weird. It doesn't seem like web hook events are being received by Kodiak for your installation or maybe just that repo.

**Comment by chdsbd** [comment]
I just forked your repository and Kodiak worked on my installation: https://github.com/chdsbd/typescript.careers/pull/1

I wonder if Kodiak isn't enabled on that repository.


Can you check your installation and ensure that Kodiak is enabled for that repository?
You can find the installation at https://github.com/settings/installations

<img width="588" alt="Screen Shot 2021-08-12 at 9 03 17 PM" src="https://user-images.githubusercontent.com/1929960/129288665-8133a6d0-598c-4dea-a889-ff39f5c09ac0.png">

**Comment by KATT** [comment]
Aw, crap, yeah, you're right. Sorry for this issue, it was totally on me.

<img width="390" alt="Screenshot 2021-08-13 at 03 04 49" src="https://user-images.githubusercontent.com/459267/129288765-a3eaea96-7ebf-49c0-884b-27e01fa4d8cd.png">


🤦 

Thanks so much for the help! 🙏

**Comment by chdsbd** [comment]
No worries! I'll add this to the troubleshooting page on the docs
