### ISSUE TITLE
Issues while building dependencies for `bot` - update uvicorn?

### ISSUE THREAD

**Issue by jbergstroem** [chdsbd/kodiak#722]
Was looking at filing a PR for #671 but ran into build-time issues with httptools 0.0.13 and uploop 0.12.2 on MacOS 11.5.2, pulled in by uvicorn 0.7.0. I won't go into detail seeing how those have since been fixed which I noticed after updating to uvicorn 0.15.0.

Would you accept a PR for updating uvicorn?

**Comment by chdsbd** [comment]
Yes, that would be great!

**Comment by jbergstroem** [comment]
Fixed in #723 (and #724)
