### ISSUE TITLE
Is it possible to make requiresConversationResolution in GET_EVENT_INFO_QUERY optional?

### ISSUE THREAD

**Issue by LeoQuote** [chdsbd/kodiak#727]
```
ERROR kodiak.queries:__init__.py:952 event='could not fetch event info' install='100' owner='playground' pr=1 repo='hello-world' res={'errors': [{'path': ['query GetEventInfo', 'repository', 'branchProtectionRules', 'nodes', 'requiresConversationResolution'], 'extensions': {'code': 'undefinedField', 'typeName': 'BranchProtectionRule', 'fieldName': 'requiresConversationResolution'}, 'locations': [{'line': 18, 'column': 9}], 'message': "Field 'requiresConversationResolution' doesn't exist on type 'BranchProtectionRule'"}]} sentry_id=None
```

My ghe instance is at version 3.0 while this filed comes at ghe 3.2 . causing checking branch protection failed.

**Comment by chdsbd** [comment]
This is the line where that's set. I guess we could define an environment variable to toggle this field on/off.

https://github.com/chdsbd/kodiak/blob/4c4ff6c2665796f640c5d32b013e042a6d0112b2/bot/kodiak/queries/__init__.py#L98

**Comment by rdmulford** [comment]
Our team has ran into the same issue after upgrading our kodiak version so just giving this issue a +1

**Comment by LeoQuote** [comment]
seems there could be better solution like this https://github.com/cli/cli/pull/2996

in this pr, they would ask if the server has that field first, then make the request
