### ISSUE TITLE
Hide kodiakhq status until automerge label has been added

### ISSUE THREAD

**Issue by paescuj** [chdsbd/kodiak#747]
We're using Kodiak for auto-merging only some specific pull requests while most of the pull request are merged by hand.

It's a bit annoying to have the "kodiakhq: status — 🛑 cannot merge (missing automerge_label: 'automerge')" message on every pull request, especially since external contributors don't have the permission to add this label anyway.

It would be very great to have an option to hide those status messages until the automerge label has been added to a pull request.

If you agree on such an option, I'm happy to submit a pull request. (I might need some initial help though as this would be my first pull request on this repository)

**Comment by rijkvanzanten** [comment]
Or as an alternative if that's not possible, make it look less like an error, maybe like:

_Before:_

**kodiakhq: status** — 🛑 cannot merge (missing automerge_label: 'automerge')

_Proposed:_

**kodiakhq: status** — Ignored (no automerge label)

**Comment by chdsbd** [comment]
I think it's good to have Kodiak set something when it examines a PR, but we can probably make the missing automerge label a little more friendly.

I think the fix would be to update this code: https://github.com/chdsbd/kodiak/blob/d4749bb41bae83cf98a4ead44455b81f6160d045/bot/kodiak/evaluation.py#L716-L720

to be something like:

```py
await api.dequeue()
await api.set_status(f"Ignored (no automerge label: {config.merge.automerge_label!r})")
```

**Comment by rijkvanzanten** [comment]
> I think it's good to have Kodiak set something when it examines a PR, but we can probably make the missing automerge label a little more friendly.

Agreed as the default behavior 👍🏻 It would be perfect if it could be user configurable, but I recognize that might be out of scope for what most users would need/want.

**Comment by chdsbd** [comment]
I'm okay with adding a config option for this.

One catch is that if Kodiak is merging a PR, but someone removes the auto merge label, we need to say something to remove the previous "merging PR" status message.
Otherwise, Yeah,

**Comment by paescuj** [comment]
> I'm okay with adding a config option for this.
> 
> One catch is that if Kodiak is merging a PR, but someone removes the auto merge label, we need to say something to remove the previous "merging PR" status message. Otherwise, Yeah,

Thanks, @chdsbd!
I've submitted a PR (#757) which addresses all of this.
