### ISSUE TITLE
kodiak down?

### ISSUE THREAD

**Issue by clxmstaab** [chdsbd/kodiak#748]
it seems the kodiak bot does not work atm.

our PR at https://github.com/complex-gmbh/php-clxproductnet/pull/1457 (private repo)  does not show a "kodiak check" at all and the automerge does not trigger

**Comment by staabm** [comment]
the bot merged the PR right now.

**Comment by chdsbd** [comment]
I rolled out a PR last night that caused this (#744). The PR splits the http handler into a separate process that dumps web hooks into a queue and the default queue worker count was too small (5). https://github.com/chdsbd/kodiak/pull/744/files#diff-df724461ffc24a0b863bb88360359f78a8ff4285e69ac493f8deba0df637b8eaR57

I've bumped up the worker count to 100 and the queue size is now at 0

**Comment by clxmstaab** [comment]
thanks for the fast feedback and fix <3.
