### ISSUE TITLE
Optional 'branch protection rule'

### ISSUE THREAD

**Issue by leikoilja** [chdsbd/kodiak#769]
Is it possible to disable kodiak being blocked by branch protection rules? 

Basically, I would like to use `kodiak` for private repo, but for those one can not enable branch protection rules without upgrading. It would be nice to allow `kodiak` to run without setting branch protection rules

**Comment by chdsbd** [comment]
Kodiak's configuration is basically tied to GitHub Branch Protection rules and the mergability checks wouldn't work without Branch Protection rules.

See this comment on a similar issue: https://github.com/chdsbd/kodiak/issues/396#issuecomment-630498895

**Comment by leikoilja** [comment]
Thank you for the answer and great package, @chdsbd.

For those in need for a solution for private repos I found https://github.com/ahmadnassri/action-dependabot-auto-merge working quite alright :)

**Comment by lestephane** [comment]
> Thank you for the answer and great package, @chdsbd.
> 
> For those in need for a solution for private repos I found https://github.com/ahmadnassri/action-dependabot-auto-merge working quite alright :)

Does this action also take care of auto rebasing out-of-date dependabot PRs? So far (without Kodiak), I've had to comment each PR with "@dependabot rebase" myself, to kickstart the rebase process...
