### ISSUE TITLE
Kodiak setup stopped working

### ISSUE THREAD

**Issue by trailsnail** [chdsbd/kodiak#774]
Hi,

since today we encouter  following problem:

open PRs are no longer updated by Kodiak.
![grafik](https://user-images.githubusercontent.com/4742603/147460043-cd20b15d-0e54-42b5-81ba-2c427058749c.png)

new PRs doesn't trigger kodiak any longer
![grafik](https://user-images.githubusercontent.com/4742603/147460170-74336f7d-2ac3-4db2-abd9-a565ad4adc20.png)

Some known problems out there?

Tool is installed correctly
![grafik](https://user-images.githubusercontent.com/4742603/147460533-fcf0879c-8a01-46ec-98ef-ab17485fd992.png)

Repos contains the `.kodiak.toml` - Worked until 2 days ago.

I don't want to have to manually update all open pull requests.

Thanks for having a look into it.

**Comment by chdsbd** [comment]
Is this still an issue? I noticed a bunch of connection issues contacting the GitHub API earlier today.

You can edit a pull request title, body, labels, or commits to trigger reevaluation.

**Comment by chdsbd** [comment]
I'm seeing intermittent timeout issues connecting to the GitHub API

**Comment by trailsnail** [comment]
> I'm seeing intermittent timeout issues connecting to the GitHub API

Same here while github actions generally
![grafik](https://user-images.githubusercontent.com/4742603/147473618-6c0ac9ea-5627-4f30-8587-cd19425e0b3d.png)

**Comment by trailsnail** [comment]
> Is this still an issue? I noticed a bunch of connection issues contacting the GitHub API earlier today.
> 
> You can edit a pull request title, body, labels, or commits to trigger reevaluation.

Still not doing what expected 🤔

**Comment by chdsbd** [comment]
I'm seeing the same issues on my staging environment

**Comment by trailsnail** [comment]
> I'm seeing the same issues on my staging environment

Seems, that github API is still in X-Mas Holidays 🤣

**Comment by chdsbd** [comment]
I've opened a support issue with GitHub. The API behavior seems a little weird at the moment.

In my staging environment, Kodiak can set a status message on a pull request, but that message doesn't appear in the UI

**Comment by trailsnail** [comment]
Thanks for investigating, I will do my merging the old way until their are some news 😉

**Comment by chdsbd** [comment]
Possibly related to this GitHub outage that was just reported: https://www.githubstatus.com/incidents/gh0vvxtlj5v7

https://news.ycombinator.com/item?id=29701059

**Comment by chdsbd** [comment]
The latency from my hosting provider (DigitalOcean) to GitHub is awful at the moment. I'm not sure why, but after making a few requests, the latency spikes up and I hit timeouts.

On my home internet, the same requests don't time out.

**Comment by chdsbd** [comment]
There haven't been any timeout errors with the GitHub API in the past 40 minutes, so I think Kodiak has recovered.

**Comment by staabm** [comment]
Github had networking issues

https://status.setup-php.com/incidents/4m7dz2c5brq0

**Comment by trailsnail** [comment]
Thanks... seems that all is working fine again. 👍🏻 

I think, this issue can be closed.

**Comment by jaredpalmer** [comment]
Kodiak is still not working on https://github.com/vercel/turborepo/blob/main/.kodiak.toml. It's been broken for just around 2 weeks

**Comment by chdsbd** [comment]
@jaredpalmer From my testing, I think that might be a separate issue. I've opened a new bug ticket here to track it: https://github.com/chdsbd/kodiak/issues/776
