### ISSUE TITLE
Merges on CircleCI to not build due to unregistered user

### ISSUE THREAD

**Issue by tdeekens** [chdsbd/kodiak#791]
When we merge a pull request using Kodiak using an auto merge label. 
Then the squash merge commit on main will not build. 

The squash commit will not build as the commit on CircleCI associates it as an unregistered user. 

One can allow unregistered users to allow builds to run but this feels not ideal. 

Is there a configuration option to allow the author or a squash merge to be the user who opened the PR. Or do co-authored fields solve this already?

Reference: https://support.circleci.com/hc/en-us/articles/4413968995099-How-to-Resolve-Error-block-unregistered-user-

**Comment by chdsbd** [comment]
Hey @tdeekens, did you find a workaround?

**Comment by tdeekens** [comment]
Thanks for asking. It seems like the issue resolved itself. It's a bit problematic for PRs which are opened by bots for instance Renovate. Then the author isn't registered in your CircleCI organisation I think.

For PRs which are opened and then merged through Renovate the issue seems to have resolved itself while I was certain it existed.
