### ISSUE TITLE
Repeated approval for self-hosted mode

### ISSUE THREAD

**Issue by tamalsaha** [chdsbd/kodiak#793]
I am using kodiak self-hosted version on Heroku. I am using auto approve for username feature. But it seems that the bot keeps repeatedly approving the pr. Here is an example:

https://github.com/bytebuilders/CHANGELOG/pull/13

kodiak file: https://github.com/bytebuilders/CHANGELOG/blob/master/.github/.kodiak.toml

I am using Heroku $7 instance in case that matters. I wonder if there is some kind to delay/multiple delivery of webhook type thing is happening.

I wonder if you have any idea how to further debug this.

**Comment by tamalsaha** [comment]
All the recent deliveries seem to be successful.
<img width="1080" alt="Screen Shot 2022-03-09 at 9 36 49 PM" src="https://user-images.githubusercontent.com/94814/157596641-93456960-4b67-4e69-bffb-2c12541b98aa.png">

**Comment by tamalsaha** [comment]
I was seeing lots of connection failure errors from Redis. I have raised the Redis connection limits to 256. Not sure that was causing problem.

**Comment by chdsbd** [comment]
Hmmm. I'm not sure about why this is happening. I'd look in Sentry or the logs and see if anything sticks out.

In the hosted version of Kodiak I haven't had any issue with connection failures from Redis.

I'd try checking your Redis connection timeout settings

**Comment by tamalsaha** [comment]
I found the problem. I had an extra space in the GITHUB_APP_NAME config var. This will fails the https://github.com/chdsbd/kodiak/pull/260/files#diff-6439f535e235b8283601300f8da0eae3cf173e371c6cfae5d8e141a36c137773R257 . Now working as expected.
