### ISSUE TITLE
Automatically merge without a label

### ISSUE THREAD

**Issue by lucleray** [chdsbd/kodiak#81]
Hi! Thank you for this very sweet github app!

We're using it but we found ourself always adding the automerge label. Could it be optional?

Maybe like this:
```toml
automerge_label = false
```

Thank you for your help 🙏

**Comment by chdsbd** [comment]
Yeah, that should be a quick change.

**Comment by chdsbd** [comment]
@lucleray Thoughts on adding another config option `require_automerge_label` instead of making `automerge_label` a union of str and bool? I think having a distinct config to enable this feature might be better.

**Comment by lucleray** [comment]
Sounds great @chdsbd

**Comment by lucleray** [comment]
@chdsbd Also, what's the difference between setting `block_on_reviews_requested` to `true` or `false`?

**Comment by chdsbd** [comment]
@lucleray If you have an open review request for a team member, kodiak won't merge the PR until that person leaves a review, even if your PR is passing all the required status checks. Does that make sense?

**Comment by lucleray** [comment]
Yes! Absolutely. So if I set it to `false`, but I have this set up:

<img width="718" alt="Capture d’écran 2019-07-25 à 02 27 31" src="https://user-images.githubusercontent.com/6616955/61837161-ccb6ed80-ae83-11e9-9ff4-1f0d1d50d610.png">

Will this rule I have on my protected branch be verified before merging?

**Comment by chdsbd** [comment]
Kodiak will always obey your branch protection rules (it will refuse to do anything without one setup). 

`block_on_reviews_requested` is in addition to branch protection rules. So even if you have all your required reviews on a PR, if you have a review request that hasn't been answered, kodiak will wait on that review until it enqueues the PR for merge.

**Comment by lucleray** [comment]
Amazing! This is perfect!

**Comment by rauchg** [comment]
![image](https://user-images.githubusercontent.com/13041/61837420-85a40a80-ae39-11e9-8624-bcf008f03fde.png)

Kodiak + ZEIT Now is a dream, tell your friends!

**Comment by rauchg** [comment]
If you set up GitHub sponsors we'd love to contribute!

**Comment by chdsbd** [comment]
Okay, I've added #82 which adds this feature. I'll get it deployed within the next hour.

@rauchg Thank you. I'll look into setting that up.

**Comment by chdsbd** [comment]
Please be sure to request any features/changes you think of.

**Comment by chdsbd** [comment]
Out of curiosity, how did you all find out about kodiak? 😄

**Comment by lucleray** [comment]
I searched "auto update PRs bot" and you were in third place: https://www.google.com/search?q=auto+update+PRs+bot

I immediately liked the logo

**Comment by chdsbd** [comment]
I've deploy a new version with this change. Let me know if there are any problems.
