### ISSUE TITLE
Bot not updating PR

### ISSUE THREAD

**Issue by Timer** [chdsbd/kodiak#83]
It seems the bot is not updating the PR with the latest changes from the `canary` branch (the default GH branch).

https://github.com/zeit/next.js/pull/7704

It's stuck as:
> kodiakhq: status — ⛴ attempting to merge PR (updating branch)

The `optimistic_updates` is set to `true`, FWIW.
Also using the new `require_automerge_label = false` option if it matters.

**Comment by chdsbd** [comment]
I think it's waiting on the tests to pass, but I'm not sure. Let me dig into this a bit.

**Comment by chdsbd** [comment]
It seems odd that it's trying to merge with that required status check not passing.

**Comment by Timer** [comment]
I had to disable the bot now per https://github.com/chdsbd/kodiak/issues/84, but yeah not sure what's going on. 🤔

**Comment by chdsbd** [comment]
I'm going to look into reproducing this more, but my first suspicion is that this may have been from the deploy.

**Comment by chdsbd** [comment]
Related, kodiak thinks [this PR](https://github.com/mcansh/blog/pull/522) is okay to merge, but when it attempts to merge it, it gets an error from the Github API, which we don't log in detail, so I'm not sure what it is.

**Comment by chdsbd** [comment]
@Timer Does this branch use the same branch protection as https://github.com/chdsbd/kodiak/issues/84#issuecomment-514865983?

**Comment by Timer** [comment]
Yes!

**Comment by chdsbd** [comment]
I've tested with the following config and I haven't been able to reproduce the issue.

![Screen Shot 2019-07-24 at 11 54 15 PM](https://user-images.githubusercontent.com/1929960/61844769-9f137980-ae6e-11e9-9f37-de2df0c38545.jpeg)

I've added some more detailed logging so hopefully we'll be able to better debug any issues that pop up.

Please reopen this ticket if this issue occurs again.

**Comment by Timer** [comment]
Great, will reenable the bot and report back.
