### ISSUE TITLE
Bot issuing duplicate comments

### ISSUE THREAD

**Issue by Timer** [chdsbd/kodiak#84]
![image](https://user-images.githubusercontent.com/616428/61839861-2d7eff80-ae5d-11e9-9f78-10c55e6052bf.png)

https://github.com/zeit/next.js/pull/8061

I had to disable the bot as it was doing this on all open PRs. 
Also, if `require_automerge_label = true`, it shouldn't specify a label in its message.

Additionally, we've customized the label `automerge_label = "lgtm"` so this message seems hard-coded.

**Comment by chdsbd** [comment]
Sorry about that. I'll try to reproduce this and get back to you.

**Comment by Timer** [comment]
Here's our [`.kodiak.toml`](https://github.com/zeit/next.js/blob/canary/.kodiak.toml) if it's helpful.

**Comment by chdsbd** [comment]
Do you mind sending me your branch protection settings for the target branch of the PR?

**Comment by Timer** [comment]
![image](https://user-images.githubusercontent.com/616428/61840565-8ea7d280-ae5f-11e9-97f2-213f22f39675.png)

**Comment by chdsbd** [comment]
Was the PR approved by a code owner when kodiak was trying to merge it?

**Comment by Timer** [comment]
Yes

**Comment by Timer** [comment]
This issue is different, OP was not approved by anyone.

**Comment by chdsbd** [comment]
Ohhhhhhh. Okay. I know a piece of this problem.

**Comment by chdsbd** [comment]
We prevent sending duplicate comments by removing the automerge label after adding the comment. Since we aren't using the automerge labels, we get a bunch of duplicate comments.

**Comment by Timer** [comment]
Just to clarify #83 and this issue (#84) were on **different** PRs.

**Comment by chdsbd** [comment]
Yeah, I think #83 must be something else.

**Comment by Timer** [comment]
Hmm, random thought. `notify_on_conflict` and `require_automerge_label` don't really work well together.

`require_automerge_label = true` needs to imply `notify_on_conflict = false`, or at least only check for conflict once already approved.

**Comment by chdsbd** [comment]
Yeah, I agree.

**Comment by Timer** [comment]
I've disabled `notify_on_conflict` for now! 😄

**Comment by chdsbd** [comment]
This should be fixed when #86 is deployed.

**Comment by sbdchd** [comment]
The bad templating should be fixed in #88

**Comment by chdsbd** [comment]
This change has been deployed.

**Comment by chdsbd** [comment]
Please reopen if this doesn't fix it. 🤞
