### ISSUE TITLE
"Delete branch on merge" randomly fails

### ISSUE THREAD

**Issue by fabiendem** [chdsbd/kodiak#841]
Hello,

We use Kodiak on our repo and rely on the `delete_branch_on_merge` feature.
While most of the time the branch gets deleted after merge as expected, it looks like sometimes the deletion just won't happen.
There is no error message visible.

We do have the following parameter in our config:
```
delete_branch_on_merge = true
```

Are you aware of such an issue?
Please let me know which extra information could be useful.

Cheers!

**Comment by chdsbd** [comment]
Hi @fabiendem,

I believe the delete_branch_on_merge isn't always reliable. I'd recommend using the "Automatically delete head branches" setting on your GitHub repository, which GitHub added after `delete_branch_on_merge` existed in Kodiak.

**Comment by fabiendem** [comment]
OK thanks for your reply and suggestion 👍 
We will do so: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches
