### ISSUE TITLE
Support dependabot's new feature to bump multiple packages at once

### ISSUE THREAD

**Issue by Maxim-Mazurok** [chdsbd/kodiak#844]
As you can see in https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/722
It says:
> Bumps [jest](https://github.com/facebook/jest/tree/HEAD/packages/jest?rgh-link-date=2022-10-01T01%3A27%3A18Z) and [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest?rgh-link-date=2022-10-01T01%3A27%3A18Z). These dependencies needed to be updated together.

Since the title reads "Bump jest and @types/jest" without mentioning the versions, I assume that kodiak couldn't check the versions:
> Dependency upgrade types are parsed from the pull request title and body.

I've been using `versions = ["major", "minor", "patch"]` now I'm trying to remove this to hopefully force it to skip version check and merge anything from dependabot.

**Comment by chdsbd** [comment]
Yeah, we should definitely add support for this. It seems like we could parse the pull request body to find the version information.

**Comment by Maxim-Mazurok** [comment]
> Yeah, we should definitely add support for this. It seems like we could parse the pull request body to find the version information.

Removing the versions field didn't help to get it auto-merged.

I've set up `action-add-labels` to add `automerge` for debepdabot PRs as a temporary(?) mesure: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/add-automerge-label.yml

**Comment by sbdchd** [comment]
Looking into this, we extract the version from renovate PR descriptions but don't for dependabot. Should be a straightforward fix!

**Comment by chdsbd** [comment]
I've deployed #845 which should fix this issue. Let me know if you have any trouble
