### ISSUE TITLE
Support CODEOWNERS for evaluating mergeability

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#87]
We only display the default status message ("Merging blocked by branch protection settings") when a PR is blocked on a required code owner review. It would be nice to display a detailed message.

Related: #96

**Comment by sbdchd** [comment]
Also need to consider how to handle future checks that github might add.

**Comment by Timer** [comment]
The PR API response has a `mergeable` property you can inspect.

**Comment by chdsbd** [comment]
I may be wrong, but I think that only considers github status checks, not Github Check suites/runs. I'll double check.

**Comment by chdsbd** [comment]
We also do check mergeable here: https://github.com/chdsbd/kodiak/blob/master/kodiak/evaluation.py#L151-L152

**Comment by chdsbd** [comment]
I'm not sure how to find code owners and if they have reviewed a PR via the Github API.

**Comment by chdsbd** [comment]
Currently if you have code owners enable and a member of the repo that is not a code owner approves the PR, kodiak will think the PR is good to merge. However when it tries to merge, it will get a `pull_request.mergeStateStatus == MergeStateStatus.BLOCKED` and trip `raise NotQueueable("Could not determine why PR is blocked")`.

**Comment by chdsbd** [comment]
To make this more clear to users we could add a check to disable merging if `requiresCodeOwnerReviews` is set on the branch protection.

**Comment by abhijithvijayan** [comment]
Had issues with this at https://github.com/onepassapp/onepass/

For now, I removed `requires Code Owner Reviews` from GitHub settings, and the bot was stuck waiting for the same count.

So I removed the label and once again assigned the same label, and then the bot picked it up and merged it.

**Comment by chdsbd** [comment]
That makes sense because Kodiak is driven by webhook events, which would only get triggered by a change to the PR.

I think the status message should be changed because Kodiak isn’t actively waiting for reviews. The next event on the PR would trigger a re-evaluation of mergeability.

**Comment by chdsbd** [comment]
Thoughts on adding this change which will completely disable kodiak for code owners? https://github.com/chdsbd/kodiak/pull/96

**Comment by abhijithvijayan** [comment]
Adding the option to disable auto merging until a review by a code owner is approved seems to be perfectly fine.

This change will only pause kodiak from merging until approved, right?

If so, it seems perfectly fine.

**Comment by chdsbd** [comment]
I was going to disable kodiak for PRs that have `requiresCodeOwnerReviews` set, but I think we can probably make CODEOWNERS work with some effort. I've updated #96 with a list of what needs to be done.

**Comment by chdsbd** [comment]
I’m going to try to work on #96 after work. It’s a bit more involved of a change because the github api doesn’t provide a simple field to query for the information, so we need to fetch and evaluate the CODEOWNERS file against all the files in a PR and match the results against any reviews provided to the PR.

**Comment by abhijithvijayan** [comment]
It seems a lot, but most repos have branch where PRs are requested to, enabled code owners review. 

After the review, the code owner can put the merge label which when set to wait for ci to pass can then be merged by the bot.

Seems better instead of disabling, dont you think?

**Comment by chdsbd** [comment]
Yeah. I’m not going to disable kodiak, we can add support for CODEOWNERS instead via #96.

**Comment by chdsbd** [comment]
@Timer @abhijithvijayan I realize now that this issue may have been misleading. Kodiak has always supported code owners, Kodiak just had a somewhat misleading default message for when it didn't understanding why a PR was blocked.

Even if Kodiak doesn't understand why a PR is blocked it will still process and merge the PR just fine. The only issue is that it doesn't display a precise reason why the PR is blocked.

I'm updating the default status message from "Could not determine why PR is blocked" to "Merging blocked by Github" in #139/#140.

I've thought about this a bit and I think it's probably unnecessary to try and figure out why github has marked a PR as BLOCKED when Github will explain why via the default Github UI. As such, I'm inclined to close this issue and #96.

Please let me know what you think about this.

**Comment by abhijithvijayan** [comment]
@chdsbd

That sounds better. 

Also, as I mentioned earlier, even if codeowners review required is enabled, if kodiak could merge it after the review was submitted by the codeowner and the label was issued, that will be a success.

As github issues the right messages, it is less concern as you said about the message Kodiak supplies. I think its good to go as long as it can merge on approved review and status label.

**Comment by chdsbd** [comment]
@abhijithvijayan Thank you for the quick response. The flow you describe is how Kodiak works now. So you should be able to use code owners right now, you'll just have the kind of ominous "Could not determine why PR is blocked" message until a code owner reviews the PR.

That default message will be updated as described on the next deployment.

I'm going to go ahead and close this issue and the corresponding PR.

Thanks for the feedback.

**Comment by chdsbd** [comment]
Okay, I spoke too soon. It turns out that to support efficient updates of PRs we _must_ calculate the mergability of a PR ourselves.

If a PR is behind master and the branch protection feature requiring branches to be up to date is enabled, Github only indicates that the PR is behind master, not that it is blocked by failing status checks!

I think after all this we _must_ implement this CODEOWNERS feature, which is disappointing because I was pretty excited about deleting a lot code 😄 , oh well.

**Comment by chdsbd** [comment]
CODEOWNERS is now supported as of #509's release via https://github.com/chdsbd/kodiak/releases/tag/v0.30.0.
