### ISSUE TITLE
Self-hosting error: Method Not Allowed

### ISSUE THREAD

**Issue by yash-zededa** [chdsbd/kodiak#870]
Hi,

I have deployed the kodiak helm chart in our k8s cluster. The app and the redis pods are running fine. 

When I try to test the integration by delivering the payload I get an error.

`Method Not Allowed`

**Comment by chdsbd** [comment]
Hi,

Do you have more context or logs. There's not much to go off of here.

I'd recommend the hosted Kodiak app via https://github.com/marketplace/kodiakhq if you're having trouble self hosting

**Comment by yash-zededa** [comment]
@chdsbd I have deployed the version `cdignam/kodiak:v0.54.0` using k8s.  I can see status OK when I hit the endpoint. 

But when github tries to deliver the payload it gives me an error.

Method not allowed

**Comment by sbdchd** [comment]
To clarify, the webhook endpoint is giving a method not allowed when GitHub tries to send a request to it?

Do you have a log line for it?

**Comment by janhartigan** [comment]
@yash-zededa come on man, don't be the guy on the internet who says "I resolved my issue" without explaining what you did to fix it. Nobody likes that guy.

**Comment by janhartigan** [comment]
OK so for anyone coming back to this issue from the future, the issue that I ignored this line in the docs:

> Use your Heroku app hostname for the webhook URL with /api/github/hook appended. Something like https://my-kodiak-app.herokuapp.com/api/github/hook.

So whatever your webhook URL is, you need to make sure you append `/api/github/hook` in the GitHub app settings.

**Comment by janhartigan** [comment]
@chdsbd @sbdchd given the above and the fact that the OP disappeared, you can probably close this issue.
