### ISSUE TITLE
Not handling missing valid signatures

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#89]
We seem to handle our calculation incorrectly here and we're getting the following response from the Github api.

```
{'message': 'Commits must have valid signatures.', 'documentation_url': 'https://help.github.com/articles/about-protected-branches'}

```

```
2019-07-25T02:45:45.227917+00:00 app[web.1]: 2019-07-25 02:45.45 get_event                      repo=owner/repo#522
2019-07-25T02:45:45.759738+00:00 app[web.1]: 2019-07-25 02:45.45 check mergeable                repo=owner/repo#522
2019-07-25T02:45:45.760105+00:00 app[web.1]: 2019-07-25 02:45.45 okay                           repo=owner/repo#522
2019-07-25T02:45:45.760456+00:00 app[web.1]: 2019-07-25 02:45.45 merge                          queue=merge_queue:install_id.owner/repo res=<MergeabilityResponse.OK: 1>
2019-07-25T02:45:46.744309+00:00 app[web.1]: 2019-07-25 02:45.46 could not merge PR             repo=owner/repo#522 res=<Response [405]> res_json={'message': 'Commits must have valid signatures.', 'documentation_url': 'https://help.github.com/articles/about-protected-branches'}
```

rel: https://help.github.com/en/articles/about-required-commit-signing

**Comment by sbdchd** [comment]
Maybe we add another case to `self.set_status()`? Can we add links in there?

**Comment by chdsbd** [comment]
Certainly, but we're not catching this in the mergeability check. This is hitting us when we try to merge the PR that we erroneously think is mergeable.

**Comment by chdsbd** [comment]
Okay, I reproduced this. The problem is if require signatures is enabled. Kodiak will try to merge the PR, but the commit kodiak tries to create through the Github api doesn't have a signature. I'm not sure there is a way for kodiak to make a signed merge commit, so we may just have to not support this setup.

**Comment by sbdchd** [comment]
The api docs don't seem to mention signing commits so we maybe SOL.

https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

**Comment by chdsbd** [comment]
After #90 we now display an error in the github check.

**Comment by staabm** [comment]
Not sure it is relatedm but it seems github apps can now sign commits
https://twitter.com/github/status/1162089808656601088?s=20

**Comment by chdsbd** [comment]
@staabm Great news. Thanks for sharing that.

**Comment by aaron-sf** [comment]
This likely to get some resolution then? Evaluating for an enterprise customer.

**Comment by chdsbd** [comment]
I know the GitHub feature doesn't work for Kodiak squashing commits, but I can't vouch for merge or rebase configurations as I don't use those.

From the GitHub post it seems like there is nothing to be done on the bot side, so if merge or rebase don't work now I think we're out of luck for now.

If anyone finds that commit signing works for merge or rebase commits created by bots I'll remove the warning added with #90.

**Comment by chdsbd** [comment]
I played around with this and it seems like squash and rebase merges fail, but a regular merge commit merge works.

Here's the API responses for the rebase merge and squash merge attempts.

rebase error

```
{
"message":"Base branch requires signed commits. Rebase merges cannot be automatically signed by GitHub",
"documentation_url":"https://help.github.com/articles/about-protected-branches"
}
```

squash error

```
{
    "message":"Commits must have valid signatures.",
    "documentation_url":"https://help.github.com/articles/about-protected-branches"
}
```

I'm going to update the logic to allow commitSignatures when `merge.method = "merge"`.

**Comment by chdsbd** [comment]
I'm closing this because Kodiak now supports commit signatures for merge commits. Rebase and squash merge methods are not allowed with commit signatures for Kodiak because they don't work with the GitHub API, by the nature of them rewriting history.
