### ISSUE TITLE
Missing required review count when branch is out-of-date

### ISSUE THREAD

**Issue by jukben** [chdsbd/kodiak#99]
Hey, first of all, thanks for that – it looks dope 🔥 . Right now we are playing with it but I guess I found a bug. In case branch is out-of-date *kodiak* is unable to update it (and merge it). 

If the branch is up-to-date automerge is OK.

Could you please help me out? 🙏 

## kodiak.toml

```
version = 1
```

## Example

![Screen Shot 2019-07-25 at 18 02 00](https://user-images.githubusercontent.com/8135252/61889768-54ddd700-af06-11e9-87ac-e70ebde7cb3e.png)

## Configuration

![Screen Shot 2019-07-25 at 18 02 29](https://user-images.githubusercontent.com/8135252/61889803-63c48980-af06-11e9-8c68-aa3d0e79a441.png)

**Comment by chdsbd** [comment]
What's your repo name? I don't see anything right off the bat that looks incorrect.

**Comment by jukben** [comment]
Sorry, the repo is private right now 😞

I will try to recreate the situation on public repository. Thanks!

**Comment by chdsbd** [comment]
No, that's fine, I was hoping to associate it with an error in the logs.

**Comment by chdsbd** [comment]
I don't see any errors in the logs, so I'm not sure why it's not working. Can you try updating the PR (changing the title, body, adding a label, etc.) and see if kodiak does something?

Kodiak only looks at a PR when it gets a webhook event for it.

**Comment by jukben** [comment]
@chdsbd That was the first thing I tried (to remove and add the `automerge` label) – till nothing. Now I tried to push something into the branch – for a second I've seen different status – but I ended up in the same state.

![Screen Shot 2019-07-25 at 18 28 13](https://user-images.githubusercontent.com/8135252/61891535-26fa9180-af0a-11e9-8fa5-d0246f9bc0a9.png)

**Comment by chdsbd** [comment]
Sorry, the logging on this project isn't super verbose, so I can't find the immediate issue. There aren't any errors in the logs, so I figure there is some miscalculation in the mergeability logic: https://github.com/chdsbd/kodiak/blob/master/kodiak/evaluation.py

I think if you could make a public repo I could better debug this issue by running the graphql query kodiak uses to fetch mergeability information. https://github.com/chdsbd/kodiak/blob/master/kodiak/queries.py#L57

**Comment by jukben** [comment]
OK, that's super weird I can't reproduce it https://github.com/jukben/sandbox.

Next step gonna be try it in different private repo in that organization from what the original example is coming from.

**Comment by chdsbd** [comment]
Yeah, I think that should enable me to run the graphql query and maybe reproduce it: https://github.com/chdsbd/kodiak/blob/master/kodiak/queries.py#L57

Are you able to reproduce in your private repo?

**Comment by jukben** [comment]
OK, I invited you into the private repository – it's complete rubbish, but you will be able to see the open PR there. So you might be able to debug it, I'm kinda curious what is the issue. 🤔

**Comment by chdsbd** [comment]
Cool. I'm in, thanks!

**Comment by chdsbd** [comment]
This is confirmed to be a bug in our logic as described in #99.

Thanks @jukben for your help!

I'm going to close in favor of #99.

I'll fix this sometime this evening. If you want to get your hands dirty the fix should only require deleting that logic and correcting the associated test.

**Comment by jukben** [comment]
Great news, @chdsbd!

I'm removing you from the repository. Glad that you have figured it out. Unfortunately, I'm super lame in Python so I will leave it for you. 

Thanks again and looking forward to use it. 💪

**Comment by chdsbd** [comment]
No worries. Thanks for helping me debug the issue!
